-- Migration 000024: Add purchase_order_id FK to receiving_tasks (S3 W2-A PO3).
-- Receiving tasks auto-generated by PO submit carry this link so the receiving
-- completion flow can update purchase_order_items and advance PO status.
ALTER TABLE receiving_tasks
  ADD COLUMN IF NOT EXISTS purchase_order_id TEXT REFERENCES purchase_orders(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_receiving_tasks_po ON receiving_tasks(purchase_order_id) WHERE purchase_order_id IS NOT NULL;
