// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: adjustment_reason_codes.sql

package sqlc

import (
	"context"
)

const createAdjustmentReasonCode = `-- name: CreateAdjustmentReasonCode :one
INSERT INTO adjustment_reason_codes (code, name, direction, is_system, display_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, direction, is_system, display_order, is_active, created_at, updated_at
`

type CreateAdjustmentReasonCodeParams struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	Direction    string `json:"direction"`
	IsSystem     bool   `json:"is_system"`
	DisplayOrder int32  `json:"display_order"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateAdjustmentReasonCode(ctx context.Context, arg CreateAdjustmentReasonCodeParams) (AdjustmentReasonCode, error) {
	row := q.db.QueryRow(ctx, createAdjustmentReasonCode,
		arg.Code,
		arg.Name,
		arg.Direction,
		arg.IsSystem,
		arg.DisplayOrder,
		arg.IsActive,
	)
	var i AdjustmentReasonCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdjustmentReasonCode = `-- name: DeleteAdjustmentReasonCode :exec
DELETE FROM adjustment_reason_codes WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteAdjustmentReasonCode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAdjustmentReasonCode, id)
	return err
}

const getAdjustmentReasonCodeByCode = `-- name: GetAdjustmentReasonCodeByCode :one
SELECT id, code, name, direction, is_system, display_order, is_active, created_at, updated_at
FROM adjustment_reason_codes
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetAdjustmentReasonCodeByCode(ctx context.Context, code string) (AdjustmentReasonCode, error) {
	row := q.db.QueryRow(ctx, getAdjustmentReasonCodeByCode, code)
	var i AdjustmentReasonCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdjustmentReasonCodeByID = `-- name: GetAdjustmentReasonCodeByID :one
SELECT id, code, name, direction, is_system, display_order, is_active, created_at, updated_at
FROM adjustment_reason_codes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAdjustmentReasonCodeByID(ctx context.Context, id string) (AdjustmentReasonCode, error) {
	row := q.db.QueryRow(ctx, getAdjustmentReasonCodeByID, id)
	var i AdjustmentReasonCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdjustmentReasonCodes = `-- name: ListAdjustmentReasonCodes :many

SELECT id, code, name, direction, is_system, display_order, is_active, created_at, updated_at
FROM adjustment_reason_codes
WHERE is_active = true
ORDER BY display_order ASC, code ASC
`

// Adjustment reason codes CRUD for sqlc. Schema: db/migrations (adjustment_reason_codes table)
func (q *Queries) ListAdjustmentReasonCodes(ctx context.Context) ([]AdjustmentReasonCode, error) {
	rows, err := q.db.Query(ctx, listAdjustmentReasonCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdjustmentReasonCode{}
	for rows.Next() {
		var i AdjustmentReasonCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Direction,
			&i.IsSystem,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdjustmentReasonCodesAdmin = `-- name: ListAdjustmentReasonCodesAdmin :many
SELECT id, code, name, direction, is_system, display_order, is_active, created_at, updated_at
FROM adjustment_reason_codes
ORDER BY display_order ASC, code ASC
`

func (q *Queries) ListAdjustmentReasonCodesAdmin(ctx context.Context) ([]AdjustmentReasonCode, error) {
	rows, err := q.db.Query(ctx, listAdjustmentReasonCodesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdjustmentReasonCode{}
	for rows.Next() {
		var i AdjustmentReasonCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Direction,
			&i.IsSystem,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdjustmentReasonCode = `-- name: UpdateAdjustmentReasonCode :one
UPDATE adjustment_reason_codes
SET
    code = $2,
    name = $3,
    direction = $4,
    display_order = $5,
    is_active = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, name, direction, is_system, display_order, is_active, created_at, updated_at
`

type UpdateAdjustmentReasonCodeParams struct {
	ID           string `json:"id"`
	Code         string `json:"code"`
	Name         string `json:"name"`
	Direction    string `json:"direction"`
	DisplayOrder int32  `json:"display_order"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) UpdateAdjustmentReasonCode(ctx context.Context, arg UpdateAdjustmentReasonCodeParams) (AdjustmentReasonCode, error) {
	row := q.db.QueryRow(ctx, updateAdjustmentReasonCode,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Direction,
		arg.DisplayOrder,
		arg.IsActive,
	)
	var i AdjustmentReasonCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Direction,
		&i.IsSystem,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
