// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: articles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const articleExistsBySku = `-- name: ArticleExistsBySku :one
SELECT EXISTS(SELECT 1 FROM articles WHERE sku = $1) AS exists
`

func (q *Queries) ArticleExistsBySku(ctx context.Context, sku string) (bool, error) {
	row := q.db.QueryRow(ctx, articleExistsBySku, sku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    sku, name, description, unit_price, presentation,
    track_by_lot, track_by_serial, track_expiration, rotation_strategy,
    min_quantity, max_quantity, image_url,
    category_id, shelf_life_in_days, safety_stock, batch_number_series,
    serial_number_series, min_order_qty, default_location_id,
    receiving_notes, shipping_notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING id, sku, name, description, unit_price, presentation,
          track_by_lot, track_by_serial, track_expiration, rotation_strategy,
          min_quantity, max_quantity, image_url, is_active,
          created_at, updated_at,
          category_id, shelf_life_in_days, safety_stock, batch_number_series,
          serial_number_series, min_order_qty, default_location_id,
          receiving_notes, shipping_notes
`

type CreateArticleParams struct {
	Sku                string         `json:"sku"`
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	UnitPrice          pgtype.Numeric `json:"unit_price"`
	Presentation       string         `json:"presentation"`
	TrackByLot         bool           `json:"track_by_lot"`
	TrackBySerial      bool           `json:"track_by_serial"`
	TrackExpiration    bool           `json:"track_expiration"`
	RotationStrategy   string         `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4    `json:"min_quantity"`
	MaxQuantity        pgtype.Int4    `json:"max_quantity"`
	ImageUrl           pgtype.Text    `json:"image_url"`
	CategoryID         pgtype.Text    `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4    `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text    `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text    `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text    `json:"default_location_id"`
	ReceivingNotes     pgtype.Text    `json:"receiving_notes"`
	ShippingNotes      pgtype.Text    `json:"shipping_notes"`
}

type CreateArticleRow struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	UnitPrice          pgtype.Numeric   `json:"unit_price"`
	Presentation       string           `json:"presentation"`
	TrackByLot         bool             `json:"track_by_lot"`
	TrackBySerial      bool             `json:"track_by_serial"`
	TrackExpiration    bool             `json:"track_expiration"`
	RotationStrategy   string           `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4      `json:"min_quantity"`
	MaxQuantity        pgtype.Int4      `json:"max_quantity"`
	ImageUrl           pgtype.Text      `json:"image_url"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	CategoryID         pgtype.Text      `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4      `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric   `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text      `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text      `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric   `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text      `json:"default_location_id"`
	ReceivingNotes     pgtype.Text      `json:"receiving_notes"`
	ShippingNotes      pgtype.Text      `json:"shipping_notes"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.Presentation,
		arg.TrackByLot,
		arg.TrackBySerial,
		arg.TrackExpiration,
		arg.RotationStrategy,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.ImageUrl,
		arg.CategoryID,
		arg.ShelfLifeInDays,
		arg.SafetyStock,
		arg.BatchNumberSeries,
		arg.SerialNumberSeries,
		arg.MinOrderQty,
		arg.DefaultLocationID,
		arg.ReceivingNotes,
		arg.ShippingNotes,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.RotationStrategy,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.ShelfLifeInDays,
		&i.SafetyStock,
		&i.BatchNumberSeries,
		&i.SerialNumberSeries,
		&i.MinOrderQty,
		&i.DefaultLocationID,
		&i.ReceivingNotes,
		&i.ShippingNotes,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, sku, name, description, unit_price, presentation,
       track_by_lot, track_by_serial, track_expiration, rotation_strategy,
       min_quantity, max_quantity, image_url, is_active,
       created_at, updated_at,
       category_id, shelf_life_in_days, safety_stock, batch_number_series,
       serial_number_series, min_order_qty, default_location_id,
       receiving_notes, shipping_notes
FROM articles
WHERE id = $1
LIMIT 1
`

type GetArticleByIDRow struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	UnitPrice          pgtype.Numeric   `json:"unit_price"`
	Presentation       string           `json:"presentation"`
	TrackByLot         bool             `json:"track_by_lot"`
	TrackBySerial      bool             `json:"track_by_serial"`
	TrackExpiration    bool             `json:"track_expiration"`
	RotationStrategy   string           `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4      `json:"min_quantity"`
	MaxQuantity        pgtype.Int4      `json:"max_quantity"`
	ImageUrl           pgtype.Text      `json:"image_url"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	CategoryID         pgtype.Text      `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4      `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric   `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text      `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text      `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric   `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text      `json:"default_location_id"`
	ReceivingNotes     pgtype.Text      `json:"receiving_notes"`
	ShippingNotes      pgtype.Text      `json:"shipping_notes"`
}

func (q *Queries) GetArticleByID(ctx context.Context, id string) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.RotationStrategy,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.ShelfLifeInDays,
		&i.SafetyStock,
		&i.BatchNumberSeries,
		&i.SerialNumberSeries,
		&i.MinOrderQty,
		&i.DefaultLocationID,
		&i.ReceivingNotes,
		&i.ShippingNotes,
	)
	return i, err
}

const getArticleBySku = `-- name: GetArticleBySku :one
SELECT id, sku, name, description, unit_price, presentation,
       track_by_lot, track_by_serial, track_expiration, rotation_strategy,
       min_quantity, max_quantity, image_url, is_active,
       created_at, updated_at,
       category_id, shelf_life_in_days, safety_stock, batch_number_series,
       serial_number_series, min_order_qty, default_location_id,
       receiving_notes, shipping_notes
FROM articles
WHERE sku = $1
LIMIT 1
`

type GetArticleBySkuRow struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	UnitPrice          pgtype.Numeric   `json:"unit_price"`
	Presentation       string           `json:"presentation"`
	TrackByLot         bool             `json:"track_by_lot"`
	TrackBySerial      bool             `json:"track_by_serial"`
	TrackExpiration    bool             `json:"track_expiration"`
	RotationStrategy   string           `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4      `json:"min_quantity"`
	MaxQuantity        pgtype.Int4      `json:"max_quantity"`
	ImageUrl           pgtype.Text      `json:"image_url"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	CategoryID         pgtype.Text      `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4      `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric   `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text      `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text      `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric   `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text      `json:"default_location_id"`
	ReceivingNotes     pgtype.Text      `json:"receiving_notes"`
	ShippingNotes      pgtype.Text      `json:"shipping_notes"`
}

func (q *Queries) GetArticleBySku(ctx context.Context, sku string) (GetArticleBySkuRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySku, sku)
	var i GetArticleBySkuRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.RotationStrategy,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.ShelfLifeInDays,
		&i.SafetyStock,
		&i.BatchNumberSeries,
		&i.SerialNumberSeries,
		&i.MinOrderQty,
		&i.DefaultLocationID,
		&i.ReceivingNotes,
		&i.ShippingNotes,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many

SELECT id, sku, name, description, unit_price, presentation,
       track_by_lot, track_by_serial, track_expiration, rotation_strategy,
       min_quantity, max_quantity, image_url, is_active,
       created_at, updated_at,
       category_id, shelf_life_in_days, safety_stock, batch_number_series,
       serial_number_series, min_order_qty, default_location_id,
       receiving_notes, shipping_notes
FROM articles
ORDER BY created_at ASC
`

type ListArticlesRow struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	UnitPrice          pgtype.Numeric   `json:"unit_price"`
	Presentation       string           `json:"presentation"`
	TrackByLot         bool             `json:"track_by_lot"`
	TrackBySerial      bool             `json:"track_by_serial"`
	TrackExpiration    bool             `json:"track_expiration"`
	RotationStrategy   string           `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4      `json:"min_quantity"`
	MaxQuantity        pgtype.Int4      `json:"max_quantity"`
	ImageUrl           pgtype.Text      `json:"image_url"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	CategoryID         pgtype.Text      `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4      `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric   `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text      `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text      `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric   `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text      `json:"default_location_id"`
	ReceivingNotes     pgtype.Text      `json:"receiving_notes"`
	ShippingNotes      pgtype.Text      `json:"shipping_notes"`
}

// Articles CRUD and related queries for sqlc
// Schema: db/migrations (articles, lots, serials tables)
func (q *Queries) ListArticles(ctx context.Context) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.UnitPrice,
			&i.Presentation,
			&i.TrackByLot,
			&i.TrackBySerial,
			&i.TrackExpiration,
			&i.RotationStrategy,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.ShelfLifeInDays,
			&i.SafetyStock,
			&i.BatchNumberSeries,
			&i.SerialNumberSeries,
			&i.MinOrderQty,
			&i.DefaultLocationID,
			&i.ReceivingNotes,
			&i.ShippingNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsBySku = `-- name: ListLotsBySku :many
SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date
FROM lots
WHERE sku = $1
`

// Lots by SKU (for UpdateArticle warnings)
func (q *Queries) ListLotsBySku(ctx context.Context, sku string) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listLotsBySku, sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.Sku,
			&i.Quantity,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LotNotes,
			&i.ManufacturedAt,
			&i.BestBeforeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSerialsBySku = `-- name: ListSerialsBySku :many
SELECT id, serial_number, sku, status, created_at, updated_at
FROM serials
WHERE sku = $1
`

// Serials by SKU (for UpdateArticle warnings)
func (q *Queries) ListSerialsBySku(ctx context.Context, sku string) ([]Serial, error) {
	rows, err := q.db.Query(ctx, listSerialsBySku, sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Serial{}
	for rows.Next() {
		var i Serial
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.Sku,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET
    sku = $2,
    name = $3,
    description = $4,
    unit_price = $5,
    presentation = $6,
    track_by_lot = $7,
    track_by_serial = $8,
    track_expiration = $9,
    rotation_strategy = $10,
    min_quantity = $11,
    max_quantity = $12,
    image_url = $13,
    is_active = $14,
    category_id = $15,
    shelf_life_in_days = $16,
    safety_stock = $17,
    batch_number_series = $18,
    serial_number_series = $19,
    min_order_qty = $20,
    default_location_id = $21,
    receiving_notes = $22,
    shipping_notes = $23,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, sku, name, description, unit_price, presentation,
          track_by_lot, track_by_serial, track_expiration, rotation_strategy,
          min_quantity, max_quantity, image_url, is_active,
          created_at, updated_at,
          category_id, shelf_life_in_days, safety_stock, batch_number_series,
          serial_number_series, min_order_qty, default_location_id,
          receiving_notes, shipping_notes
`

type UpdateArticleParams struct {
	ID                 string         `json:"id"`
	Sku                string         `json:"sku"`
	Name               string         `json:"name"`
	Description        pgtype.Text    `json:"description"`
	UnitPrice          pgtype.Numeric `json:"unit_price"`
	Presentation       string         `json:"presentation"`
	TrackByLot         bool           `json:"track_by_lot"`
	TrackBySerial      bool           `json:"track_by_serial"`
	TrackExpiration    bool           `json:"track_expiration"`
	RotationStrategy   string         `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4    `json:"min_quantity"`
	MaxQuantity        pgtype.Int4    `json:"max_quantity"`
	ImageUrl           pgtype.Text    `json:"image_url"`
	IsActive           pgtype.Bool    `json:"is_active"`
	CategoryID         pgtype.Text    `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4    `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text    `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text    `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text    `json:"default_location_id"`
	ReceivingNotes     pgtype.Text    `json:"receiving_notes"`
	ShippingNotes      pgtype.Text    `json:"shipping_notes"`
}

type UpdateArticleRow struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	UnitPrice          pgtype.Numeric   `json:"unit_price"`
	Presentation       string           `json:"presentation"`
	TrackByLot         bool             `json:"track_by_lot"`
	TrackBySerial      bool             `json:"track_by_serial"`
	TrackExpiration    bool             `json:"track_expiration"`
	RotationStrategy   string           `json:"rotation_strategy"`
	MinQuantity        pgtype.Int4      `json:"min_quantity"`
	MaxQuantity        pgtype.Int4      `json:"max_quantity"`
	ImageUrl           pgtype.Text      `json:"image_url"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	CategoryID         pgtype.Text      `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4      `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric   `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text      `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text      `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric   `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text      `json:"default_location_id"`
	ReceivingNotes     pgtype.Text      `json:"receiving_notes"`
	ShippingNotes      pgtype.Text      `json:"shipping_notes"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.Presentation,
		arg.TrackByLot,
		arg.TrackBySerial,
		arg.TrackExpiration,
		arg.RotationStrategy,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.ImageUrl,
		arg.IsActive,
		arg.CategoryID,
		arg.ShelfLifeInDays,
		arg.SafetyStock,
		arg.BatchNumberSeries,
		arg.SerialNumberSeries,
		arg.MinOrderQty,
		arg.DefaultLocationID,
		arg.ReceivingNotes,
		arg.ShippingNotes,
	)
	var i UpdateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.RotationStrategy,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.ShelfLifeInDays,
		&i.SafetyStock,
		&i.BatchNumberSeries,
		&i.SerialNumberSeries,
		&i.MinOrderQty,
		&i.DefaultLocationID,
		&i.ReceivingNotes,
		&i.ShippingNotes,
	)
	return i, err
}
