// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: articles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const articleExistsBySku = `-- name: ArticleExistsBySku :one
SELECT EXISTS(SELECT 1 FROM articles WHERE sku = $1) AS exists
`

func (q *Queries) ArticleExistsBySku(ctx context.Context, sku string) (bool, error) {
	row := q.db.QueryRow(ctx, articleExistsBySku, sku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    sku, name, description, unit_price, presentation,
    track_by_lot, track_by_serial, track_expiration,
    min_quantity, max_quantity, image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, sku, name, description, unit_price, presentation,
          track_by_lot, track_by_serial, track_expiration,
          min_quantity, max_quantity, image_url, is_active,
          created_at, updated_at
`

type CreateArticleParams struct {
	Sku             string         `json:"sku"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	Presentation    string         `json:"presentation"`
	TrackByLot      bool           `json:"track_by_lot"`
	TrackBySerial   bool           `json:"track_by_serial"`
	TrackExpiration bool           `json:"track_expiration"`
	MinQuantity     pgtype.Int4    `json:"min_quantity"`
	MaxQuantity     pgtype.Int4    `json:"max_quantity"`
	ImageUrl        pgtype.Text    `json:"image_url"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.Presentation,
		arg.TrackByLot,
		arg.TrackBySerial,
		arg.TrackExpiration,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.ImageUrl,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, sku, name, description, unit_price, presentation,
       track_by_lot, track_by_serial, track_expiration,
       min_quantity, max_quantity, image_url, is_active,
       created_at, updated_at
FROM articles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetArticleByID(ctx context.Context, id string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleBySku = `-- name: GetArticleBySku :one
SELECT id, sku, name, description, unit_price, presentation,
       track_by_lot, track_by_serial, track_expiration,
       min_quantity, max_quantity, image_url, is_active,
       created_at, updated_at
FROM articles
WHERE sku = $1
LIMIT 1
`

func (q *Queries) GetArticleBySku(ctx context.Context, sku string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySku, sku)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many

SELECT id, sku, name, description, unit_price, presentation,
       track_by_lot, track_by_serial, track_expiration,
       min_quantity, max_quantity, image_url, is_active,
       created_at, updated_at
FROM articles
ORDER BY created_at ASC
`

// Articles CRUD and related queries for sqlc
// Schema: db/migrations (articles, lots, serials tables)
func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.UnitPrice,
			&i.Presentation,
			&i.TrackByLot,
			&i.TrackBySerial,
			&i.TrackExpiration,
			&i.MinQuantity,
			&i.MaxQuantity,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsBySku = `-- name: ListLotsBySku :many
SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status
FROM lots
WHERE sku = $1
`

// Lots by SKU (for UpdateArticle warnings)
func (q *Queries) ListLotsBySku(ctx context.Context, sku string) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listLotsBySku, sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.Sku,
			&i.Quantity,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSerialsBySku = `-- name: ListSerialsBySku :many
SELECT id, serial_number, sku, status, created_at, updated_at
FROM serials
WHERE sku = $1
`

// Serials by SKU (for UpdateArticle warnings)
func (q *Queries) ListSerialsBySku(ctx context.Context, sku string) ([]Serial, error) {
	rows, err := q.db.Query(ctx, listSerialsBySku, sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Serial{}
	for rows.Next() {
		var i Serial
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.Sku,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET
    sku = $2,
    name = $3,
    description = $4,
    unit_price = $5,
    presentation = $6,
    track_by_lot = $7,
    track_by_serial = $8,
    track_expiration = $9,
    min_quantity = $10,
    max_quantity = $11,
    image_url = $12,
    is_active = $13,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, sku, name, description, unit_price, presentation,
          track_by_lot, track_by_serial, track_expiration,
          min_quantity, max_quantity, image_url, is_active,
          created_at, updated_at
`

type UpdateArticleParams struct {
	ID              string         `json:"id"`
	Sku             string         `json:"sku"`
	Name            string         `json:"name"`
	Description     pgtype.Text    `json:"description"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	Presentation    string         `json:"presentation"`
	TrackByLot      bool           `json:"track_by_lot"`
	TrackBySerial   bool           `json:"track_by_serial"`
	TrackExpiration bool           `json:"track_expiration"`
	MinQuantity     pgtype.Int4    `json:"min_quantity"`
	MaxQuantity     pgtype.Int4    `json:"max_quantity"`
	ImageUrl        pgtype.Text    `json:"image_url"`
	IsActive        pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.Presentation,
		arg.TrackByLot,
		arg.TrackBySerial,
		arg.TrackExpiration,
		arg.MinQuantity,
		arg.MaxQuantity,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.Presentation,
		&i.TrackByLot,
		&i.TrackBySerial,
		&i.TrackExpiration,
		&i.MinQuantity,
		&i.MaxQuantity,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
