// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE
    ($1::text IS NULL OR user_id = $1)
    AND ($2::text IS NULL OR resource_type = $2)
    AND ($3::text IS NULL OR resource_id = $3)
    AND ($4::text IS NULL OR action = $4)
    AND ($5::timestamptz IS NULL OR created_at >= $5)
    AND ($6::timestamptz IS NULL OR created_at <= $6)
`

type CountAuditLogsParams struct {
	FilterUserID       pgtype.Text        `json:"filter_user_id"`
	FilterResourceType pgtype.Text        `json:"filter_resource_type"`
	FilterResourceID   pgtype.Text        `json:"filter_resource_id"`
	FilterAction       pgtype.Text        `json:"filter_action"`
	FilterStartDate    pgtype.Timestamptz `json:"filter_start_date"`
	FilterEndDate      pgtype.Timestamptz `json:"filter_end_date"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.FilterUserID,
		arg.FilterResourceType,
		arg.FilterResourceID,
		arg.FilterAction,
		arg.FilterStartDate,
		arg.FilterEndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
    user_id, action, resource_type, resource_id,
    old_value, new_value, ip_address, user_agent, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, action, resource_type, resource_id,
          old_value, new_value, ip_address, user_agent, metadata, created_at
`

type CreateAuditLogParams struct {
	UserID       pgtype.Text `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	OldValue     []byte      `json:"old_value"`
	NewValue     []byte      `json:"new_value"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
}

// Audit logs: who did what, when, how
// Schema: db/migrations (000003_audit_logs_schema)
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.OldValue,
		arg.NewValue,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.OldValue,
		&i.NewValue,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id,
       old_value, new_value, ip_address, user_agent, metadata, created_at
FROM audit_logs
WHERE
    ($3::text IS NULL OR user_id = $3)
    AND ($4::text IS NULL OR resource_type = $4)
    AND ($5::text IS NULL OR resource_id = $5)
    AND ($6::text IS NULL OR action = $6)
    AND ($7::timestamptz IS NULL OR created_at >= $7)
    AND ($8::timestamptz IS NULL OR created_at <= $8)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit              int32              `json:"limit"`
	Offset             int32              `json:"offset"`
	FilterUserID       pgtype.Text        `json:"filter_user_id"`
	FilterResourceType pgtype.Text        `json:"filter_resource_type"`
	FilterResourceID   pgtype.Text        `json:"filter_resource_id"`
	FilterAction       pgtype.Text        `json:"filter_action"`
	FilterStartDate    pgtype.Timestamptz `json:"filter_start_date"`
	FilterEndDate      pgtype.Timestamptz `json:"filter_end_date"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.FilterUserID,
		arg.FilterResourceType,
		arg.FilterResourceID,
		arg.FilterAction,
		arg.FilterStartDate,
		arg.FilterEndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.OldValue,
			&i.NewValue,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
