// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (id, tenant_id, name, parent_id, is_active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, tenant_id, name, parent_id, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	ParentID pgtype.Text `json:"parent_id"`
}

// Categories CRUD for sqlc
// Schema: db/migrations/000018_sprint_s2.up.sql (categories table)
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, tenant_id, name, parent_id, is_active, created_at, updated_at
FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByTenant = `-- name: ListCategoriesByTenant :many
SELECT id, tenant_id, name, parent_id, is_active, created_at, updated_at
FROM categories
WHERE tenant_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
  -- TODO(S3/MA4): escape ILIKE wildcards with replace(search,'%','\%') ESCAPE '\' to prevent
  -- DoS via catastrophic backtracking on strings containing many '%' or '_' characters.
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%')
ORDER BY name ASC
LIMIT COALESCE($5::int, 200)
OFFSET COALESCE($4::int, 0)
`

type ListCategoriesByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	IsActive pgtype.Bool `json:"is_active"`
	Search   pgtype.Text `json:"search"`
	Offset   pgtype.Int4 `json:"offset"`
	Limit    pgtype.Int4 `json:"limit"`
}

// M8: Push search/is_active filters and pagination to SQL (HR1 deferred).
// Pass NULL for any optional param to skip that filter.
// sqlc.narg() used so generated struct has named fields (IsActive, Search, Limit, Offset)
// instead of positional Column2…Column5 names that sqlc v1.29.0 infers for $N::type IS NULL patterns.
func (q *Queries) ListCategoriesByTenant(ctx context.Context, arg ListCategoriesByTenantParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByTenant,
		arg.TenantID,
		arg.IsActive,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, parent_id = $3, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, parent_id, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.Text `json:"parent_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
