// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one

INSERT INTO clients (id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, true, $11)
RETURNING id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by, created_at, updated_at
`

type CreateClientParams struct {
	ID        string      `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Type      string      `json:"type"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Address   pgtype.Text `json:"address"`
	TaxID     pgtype.Text `json:"tax_id"`
	Notes     pgtype.Text `json:"notes"`
	CreatedBy pgtype.Text `json:"created_by"`
}

// Clients CRUD for sqlc
// Schema: db/migrations/000018_sprint_s2.up.sql (clients table)
func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.TaxID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by, created_at, updated_at
FROM clients WHERE id = $1
`

// Internal use only: no tenant filter. Use GetClientByIDForTenant for HTTP responses (HR1-M3).
func (q *Queries) GetClientByID(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByIDForTenant = `-- name: GetClientByIDForTenant :one
SELECT id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by, created_at, updated_at
FROM clients WHERE id = $1 AND tenant_id = $2
`

type GetClientByIDForTenantParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// HR1-M3: tenant_id guard prevents cross-tenant client enumeration via HTTP.
func (q *Queries) GetClientByIDForTenant(ctx context.Context, arg GetClientByIDForTenantParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByIDForTenant, arg.ID, arg.TenantID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByTenantAndCode = `-- name: GetClientByTenantAndCode :one
SELECT id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by, created_at, updated_at
FROM clients WHERE tenant_id = $1 AND code = $2
`

type GetClientByTenantAndCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetClientByTenantAndCode(ctx context.Context, arg GetClientByTenantAndCodeParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByTenantAndCode, arg.TenantID, arg.Code)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientsByTenant = `-- name: ListClientsByTenant :many
SELECT id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by, created_at, updated_at
FROM clients
WHERE tenant_id = $1
  AND ($2::text IS NULL OR type = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
  AND ($4::text IS NULL OR (name ILIKE '%' || $4 || '%' OR code ILIKE '%' || $4 || '%'))
ORDER BY name ASC
LIMIT COALESCE($5::int, 100)
OFFSET COALESCE($6::int, 0)
`

// ListClientsByTenantParams holds optional filter params for ListClientsByTenant.
// Use pgtype.Text{} (Valid:false) / pgtype.Bool{} (Valid:false) / pgtype.Int4{} (Valid:false)
// to pass NULL and skip a filter.  M8: fields renamed from sqlc Column* defaults.
type ListClientsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     pgtype.Text `json:"type"`
	IsActive pgtype.Bool `json:"is_active"`
	Search   pgtype.Text `json:"search"`
	Limit    pgtype.Int4 `json:"limit"`
	Offset   pgtype.Int4 `json:"offset"`
}

// M8: Push type/is_active/search filters and pagination to SQL (HR1 deferred).
// Pass NULL for any optional param to skip that filter.
func (q *Queries) ListClientsByTenant(ctx context.Context, arg ListClientsByTenantParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClientsByTenant,
		arg.TenantID,
		arg.Type,
		arg.IsActive,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Code,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.TaxID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteClient = `-- name: SoftDeleteClient :exec
UPDATE clients SET is_active = false, updated_at = now() WHERE id = $1 AND tenant_id = $2
`

type SoftDeleteClientParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// HR1-M3: tenant_id guard prevents cross-tenant soft-delete.
func (q *Queries) SoftDeleteClient(ctx context.Context, arg SoftDeleteClientParams) error {
	_, err := q.db.Exec(ctx, softDeleteClient, arg.ID, arg.TenantID)
	return err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET type = $2, code = $3, name = $4, email = $5, phone = $6, address = $7, tax_id = $8, notes = $9, updated_at = now()
WHERE id = $1 AND tenant_id = $10
RETURNING id, tenant_id, type, code, name, email, phone, address, tax_id, notes, is_active, created_by, created_at, updated_at
`

type UpdateClientParams struct {
	ID       string      `json:"id"`
	Type     string      `json:"type"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
	Address  pgtype.Text `json:"address"`
	TaxID    pgtype.Text `json:"tax_id"`
	Notes    pgtype.Text `json:"notes"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// HR1-M3: tenant_id guard prevents cross-tenant update.
func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.TaxID,
		arg.Notes,
		arg.TenantID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
