// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: location_types.sql

package sqlc

import (
	"context"
)

const createLocationType = `-- name: CreateLocationType :one
INSERT INTO location_types (code, name, sort_order, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, sort_order, is_active, created_at, updated_at
`

type CreateLocationTypeParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreateLocationType(ctx context.Context, arg CreateLocationTypeParams) (LocationType, error) {
	row := q.db.QueryRow(ctx, createLocationType,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i LocationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocationType = `-- name: DeleteLocationType :exec
DELETE FROM location_types WHERE id = $1
`

func (q *Queries) DeleteLocationType(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocationType, id)
	return err
}

const getLocationTypeByCode = `-- name: GetLocationTypeByCode :one
SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM location_types
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetLocationTypeByCode(ctx context.Context, code string) (LocationType, error) {
	row := q.db.QueryRow(ctx, getLocationTypeByCode, code)
	var i LocationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationTypeByID = `-- name: GetLocationTypeByID :one
SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM location_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLocationTypeByID(ctx context.Context, id string) (LocationType, error) {
	row := q.db.QueryRow(ctx, getLocationTypeByID, id)
	var i LocationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationTypes = `-- name: ListLocationTypes :many

SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM location_types
WHERE is_active = true
ORDER BY sort_order ASC, code ASC
`

// Location types CRUD for sqlc. Schema: db/migrations (location_types table)
func (q *Queries) ListLocationTypes(ctx context.Context) ([]LocationType, error) {
	rows, err := q.db.Query(ctx, listLocationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationType{}
	for rows.Next() {
		var i LocationType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationTypesAdmin = `-- name: ListLocationTypesAdmin :many
SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM location_types
ORDER BY sort_order ASC, code ASC
`

func (q *Queries) ListLocationTypesAdmin(ctx context.Context) ([]LocationType, error) {
	rows, err := q.db.Query(ctx, listLocationTypesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationType{}
	for rows.Next() {
		var i LocationType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationTypeExistsByCode = `-- name: LocationTypeExistsByCode :one
SELECT EXISTS(SELECT 1 FROM location_types WHERE code = $1) AS exists
`

func (q *Queries) LocationTypeExistsByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, locationTypeExistsByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocationType = `-- name: UpdateLocationType :one
UPDATE location_types
SET
    code = $2,
    name = $3,
    sort_order = $4,
    is_active = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, name, sort_order, is_active, created_at, updated_at
`

type UpdateLocationTypeParams struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) UpdateLocationType(ctx context.Context, arg UpdateLocationTypeParams) (LocationType, error) {
	row := q.db.QueryRow(ctx, updateLocationType,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i LocationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
