// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (location_code, description, zone, type, is_active, is_way_out, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at, tenant_id
`

type CreateLocationParams struct {
	LocationCode string      `json:"location_code"`
	Description  pgtype.Text `json:"description"`
	Zone         pgtype.Text `json:"zone"`
	Type         string      `json:"type"`
	IsActive     bool        `json:"is_active"`
	IsWayOut     bool        `json:"is_way_out"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

type CreateLocationRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
}

// S3.5 W2-A: tenant_id is required and provided by the controller layer.
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (CreateLocationRow, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.LocationCode,
		arg.Description,
		arg.Zone,
		arg.Type,
		arg.IsActive,
		arg.IsWayOut,
		arg.TenantID,
	)
	var i CreateLocationRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteLocationForTenant = `-- name: DeleteLocationForTenant :exec
DELETE FROM locations WHERE id = $1 AND tenant_id = $2
`

type DeleteLocationForTenantParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// S3.5 W2-A: tenant_id guard prevents cross-tenant delete.
func (q *Queries) DeleteLocationForTenant(ctx context.Context, arg DeleteLocationForTenantParams) error {
	_, err := q.db.Exec(ctx, deleteLocationForTenant, arg.ID, arg.TenantID)
	return err
}

const getLocationByIDForTenant = `-- name: GetLocationByIDForTenant :one
SELECT id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at, tenant_id
FROM locations
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetLocationByIDForTenantParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetLocationByIDForTenantRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
}

// S3.5 W2-A: tenant_id guard prevents cross-tenant id lookup.
func (q *Queries) GetLocationByIDForTenant(ctx context.Context, arg GetLocationByIDForTenantParams) (GetLocationByIDForTenantRow, error) {
	row := q.db.QueryRow(ctx, getLocationByIDForTenant, arg.ID, arg.TenantID)
	var i GetLocationByIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getLocationByLocationCodeForTenant = `-- name: GetLocationByLocationCodeForTenant :one
SELECT id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at, tenant_id
FROM locations
WHERE location_code = $1 AND tenant_id = $2
LIMIT 1
`

type GetLocationByLocationCodeForTenantParams struct {
	LocationCode string      `json:"location_code"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

type GetLocationByLocationCodeForTenantRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
}

// S3.5 W2-A: tenant_id guard. Used as fallback by ID lookup when caller passed a code.
func (q *Queries) GetLocationByLocationCodeForTenant(ctx context.Context, arg GetLocationByLocationCodeForTenantParams) (GetLocationByLocationCodeForTenantRow, error) {
	row := q.db.QueryRow(ctx, getLocationByLocationCodeForTenant, arg.LocationCode, arg.TenantID)
	var i GetLocationByLocationCodeForTenantRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listLocationsByTenant = `-- name: ListLocationsByTenant :many

SELECT id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at, tenant_id
FROM locations
WHERE tenant_id = $1
ORDER BY created_at ASC
`

type ListLocationsByTenantRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
}

// Locations CRUD for sqlc
// Schema: db/migrations (locations table; tenant_id added in 000032).
// All HTTP-facing endpoints MUST filter by tenant_id (S3.5 W2-A).
// S3.5 W2-A: tenant_id guard prevents cross-tenant location enumeration.
func (q *Queries) ListLocationsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListLocationsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listLocationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationsByTenantRow{}
	for rows.Next() {
		var i ListLocationsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationCode,
			&i.Description,
			&i.Zone,
			&i.Type,
			&i.IsActive,
			&i.IsWayOut,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExistsByLocationCodeForTenant = `-- name: LocationExistsByLocationCodeForTenant :one
SELECT EXISTS(
  SELECT 1 FROM locations WHERE location_code = $1 AND tenant_id = $2
) AS exists
`

type LocationExistsByLocationCodeForTenantParams struct {
	LocationCode string      `json:"location_code"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

// S3.5 W2-A: tenant_id guard. Used by Create to enforce per-tenant unique location_code.
func (q *Queries) LocationExistsByLocationCodeForTenant(ctx context.Context, arg LocationExistsByLocationCodeForTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, locationExistsByLocationCodeForTenant, arg.LocationCode, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocationForTenant = `-- name: UpdateLocationForTenant :one
UPDATE locations
SET
    location_code = $2,
    description = $3,
    zone = $4,
    type = $5,
    is_active = $6,
    is_way_out = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $8
RETURNING id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at, tenant_id
`

type UpdateLocationForTenantParams struct {
	ID           string      `json:"id"`
	LocationCode string      `json:"location_code"`
	Description  pgtype.Text `json:"description"`
	Zone         pgtype.Text `json:"zone"`
	Type         string      `json:"type"`
	IsActive     bool        `json:"is_active"`
	IsWayOut     bool        `json:"is_way_out"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

type UpdateLocationForTenantRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
}

// S3.5 W2-A: tenant_id guard prevents cross-tenant update.
func (q *Queries) UpdateLocationForTenant(ctx context.Context, arg UpdateLocationForTenantParams) (UpdateLocationForTenantRow, error) {
	row := q.db.QueryRow(ctx, updateLocationForTenant,
		arg.ID,
		arg.LocationCode,
		arg.Description,
		arg.Zone,
		arg.Type,
		arg.IsActive,
		arg.IsWayOut,
		arg.TenantID,
	)
	var i UpdateLocationForTenantRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
