// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (location_code, description, zone, type, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, location_code, description, zone, type, is_active, created_at, updated_at
`

type CreateLocationParams struct {
	LocationCode string      `json:"location_code"`
	Description  pgtype.Text `json:"description"`
	Zone         pgtype.Text `json:"zone"`
	Type         string      `json:"type"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.LocationCode,
		arg.Description,
		arg.Zone,
		arg.Type,
		arg.IsActive,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, location_code, description, zone, type, is_active, created_at, updated_at
FROM locations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLocationByID(ctx context.Context, id string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationByLocationCode = `-- name: GetLocationByLocationCode :one
SELECT id, location_code, description, zone, type, is_active, created_at, updated_at
FROM locations
WHERE location_code = $1
LIMIT 1
`

func (q *Queries) GetLocationByLocationCode(ctx context.Context, locationCode string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByLocationCode, locationCode)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many

SELECT id, location_code, description, zone, type, is_active, created_at, updated_at
FROM locations
ORDER BY created_at ASC
`

// Locations CRUD for sqlc
// Schema: db/migrations (locations table)
func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.LocationCode,
			&i.Description,
			&i.Zone,
			&i.Type,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExistsByLocationCode = `-- name: LocationExistsByLocationCode :one
SELECT EXISTS(SELECT 1 FROM locations WHERE location_code = $1) AS exists
`

func (q *Queries) LocationExistsByLocationCode(ctx context.Context, locationCode string) (bool, error) {
	row := q.db.QueryRow(ctx, locationExistsByLocationCode, locationCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
    location_code = $2,
    description = $3,
    zone = $4,
    type = $5,
    is_active = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, location_code, description, zone, type, is_active, created_at, updated_at
`

type UpdateLocationParams struct {
	ID           string      `json:"id"`
	LocationCode string      `json:"location_code"`
	Description  pgtype.Text `json:"description"`
	Zone         pgtype.Text `json:"zone"`
	Type         string      `json:"type"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.LocationCode,
		arg.Description,
		arg.Zone,
		arg.Type,
		arg.IsActive,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
