// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (location_code, description, zone, type, is_active, is_way_out)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at
`

type CreateLocationParams struct {
	LocationCode string      `json:"location_code"`
	Description  pgtype.Text `json:"description"`
	Zone         pgtype.Text `json:"zone"`
	Type         string      `json:"type"`
	IsActive     bool        `json:"is_active"`
	IsWayOut     bool        `json:"is_way_out"`
}

type CreateLocationRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (CreateLocationRow, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.LocationCode,
		arg.Description,
		arg.Zone,
		arg.Type,
		arg.IsActive,
		arg.IsWayOut,
	)
	var i CreateLocationRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at
FROM locations
WHERE id = $1
LIMIT 1
`

type GetLocationByIDRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetLocationByID(ctx context.Context, id string) (GetLocationByIDRow, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i GetLocationByIDRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationByLocationCode = `-- name: GetLocationByLocationCode :one
SELECT id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at
FROM locations
WHERE location_code = $1
LIMIT 1
`

type GetLocationByLocationCodeRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetLocationByLocationCode(ctx context.Context, locationCode string) (GetLocationByLocationCodeRow, error) {
	row := q.db.QueryRow(ctx, getLocationByLocationCode, locationCode)
	var i GetLocationByLocationCodeRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many

SELECT id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at
FROM locations
ORDER BY created_at ASC
`

type ListLocationsRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// Locations CRUD for sqlc
// Schema: db/migrations (locations table)
func (q *Queries) ListLocations(ctx context.Context) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationsRow{}
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationCode,
			&i.Description,
			&i.Zone,
			&i.Type,
			&i.IsActive,
			&i.IsWayOut,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExistsByLocationCode = `-- name: LocationExistsByLocationCode :one
SELECT EXISTS(SELECT 1 FROM locations WHERE location_code = $1) AS exists
`

func (q *Queries) LocationExistsByLocationCode(ctx context.Context, locationCode string) (bool, error) {
	row := q.db.QueryRow(ctx, locationExistsByLocationCode, locationCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
    location_code = $2,
    description = $3,
    zone = $4,
    type = $5,
    is_active = $6,
    is_way_out = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, location_code, description, zone, type, is_active, is_way_out, created_at, updated_at
`

type UpdateLocationParams struct {
	ID           string      `json:"id"`
	LocationCode string      `json:"location_code"`
	Description  pgtype.Text `json:"description"`
	Zone         pgtype.Text `json:"zone"`
	Type         string      `json:"type"`
	IsActive     bool        `json:"is_active"`
	IsWayOut     bool        `json:"is_way_out"`
}

type UpdateLocationRow struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	IsWayOut     bool             `json:"is_way_out"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (UpdateLocationRow, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.LocationCode,
		arg.Description,
		arg.Zone,
		arg.Type,
		arg.IsActive,
		arg.IsWayOut,
	)
	var i UpdateLocationRow
	err := row.Scan(
		&i.ID,
		&i.LocationCode,
		&i.Description,
		&i.Zone,
		&i.Type,
		&i.IsActive,
		&i.IsWayOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
