// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLot = `-- name: CreateLot :one
INSERT INTO lots (lot_number, sku, quantity, expiration_date, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
          lot_notes, manufactured_at, best_before_date
`

type CreateLotParams struct {
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	Status         string           `json:"status"`
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (Lot, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.LotNumber,
		arg.Sku,
		arg.Quantity,
		arg.ExpirationDate,
		arg.Status,
	)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
	)
	return i, err
}

const deleteLot = `-- name: DeleteLot :exec
DELETE FROM lots WHERE id = $1
`

func (q *Queries) DeleteLot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLot, id)
	return err
}

const getLotByID = `-- name: GetLotByID :one
SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date
FROM lots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLotByID(ctx context.Context, id string) (Lot, error) {
	row := q.db.QueryRow(ctx, getLotByID, id)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
	)
	return i, err
}

const listLots = `-- name: ListLots :many

SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date
FROM lots
ORDER BY created_at DESC
`

// Lots CRUD for sqlc
// Schema: db/migrations (lots table)
func (q *Queries) ListLots(ctx context.Context) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listLots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.Sku,
			&i.Quantity,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LotNotes,
			&i.ManufacturedAt,
			&i.BestBeforeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLot = `-- name: UpdateLot :one
UPDATE lots
SET
    lot_number = $2,
    sku = $3,
    quantity = $4,
    expiration_date = $5,
    status = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
          lot_notes, manufactured_at, best_before_date
`

type UpdateLotParams struct {
	ID             string           `json:"id"`
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	Status         string           `json:"status"`
}

func (q *Queries) UpdateLot(ctx context.Context, arg UpdateLotParams) (Lot, error) {
	row := q.db.QueryRow(ctx, updateLot,
		arg.ID,
		arg.LotNumber,
		arg.Sku,
		arg.Quantity,
		arg.ExpirationDate,
		arg.Status,
	)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
	)
	return i, err
}
