// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLot = `-- name: CreateLot :one
INSERT INTO lots (lot_number, sku, quantity, expiration_date, status,
                 lot_notes, manufactured_at, best_before_date, tenant_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
          lot_notes, manufactured_at, best_before_date, tenant_id
`

type CreateLotParams struct {
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	Status         string           `json:"status"`
	LotNotes       pgtype.Text      `json:"lot_notes"`
	ManufacturedAt pgtype.Date      `json:"manufactured_at"`
	BestBeforeDate pgtype.Date      `json:"best_before_date"`
	TenantID       pgtype.UUID      `json:"tenant_id"`
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (Lot, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.LotNumber,
		arg.Sku,
		arg.Quantity,
		arg.ExpirationDate,
		arg.Status,
		arg.LotNotes,
		arg.ManufacturedAt,
		arg.BestBeforeDate,
		arg.TenantID,
	)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
		&i.TenantID,
	)
	return i, err
}

const deleteLot = `-- name: DeleteLot :exec
DELETE FROM lots WHERE id = $1 AND tenant_id = $2
`

type DeleteLotParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Tenant guard prevents cross-tenant deletes (S3.5 W2-B).
func (q *Queries) DeleteLot(ctx context.Context, arg DeleteLotParams) error {
	_, err := q.db.Exec(ctx, deleteLot, arg.ID, arg.TenantID)
	return err
}

const getLotByID = `-- name: GetLotByID :one
SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date, tenant_id
FROM lots
WHERE id = $1
LIMIT 1
`

// Internal use only: no tenant filter. Use GetLotByIDForTenant for HTTP callers.
func (q *Queries) GetLotByID(ctx context.Context, id string) (Lot, error) {
	row := q.db.QueryRow(ctx, getLotByID, id)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
		&i.TenantID,
	)
	return i, err
}

const getLotByIDForTenant = `-- name: GetLotByIDForTenant :one
SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date, tenant_id
FROM lots
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetLotByIDForTenantParams struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Tenant guard prevents cross-tenant lot enumeration via HTTP (S3.5 W2-B).
func (q *Queries) GetLotByIDForTenant(ctx context.Context, arg GetLotByIDForTenantParams) (Lot, error) {
	row := q.db.QueryRow(ctx, getLotByIDForTenant, arg.ID, arg.TenantID)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
		&i.TenantID,
	)
	return i, err
}

const listLots = `-- name: ListLots :many

SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date, tenant_id
FROM lots
WHERE tenant_id = $1
ORDER BY created_at DESC
`

// Lots CRUD for sqlc
// Schema: db/migrations (lots table; tenant_id added in 000030)
// S3.5 W2-B: every public query is tenant-scoped. Internal helpers (GetLotByID) keep
// the un-scoped variant for cross-domain joins (lot trace, picking task validation)
// where the caller already proved tenancy via the parent record.
//
// Column order in SELECT/RETURNING must match db/sqlc/models.go::Lot (Postgres appends
// tenant_id at the end after the 000030 migration), otherwise sqlc generates per-query
// Row structs instead of returning the shared Lot model.
// Returns all lots for a tenant, sorted by created_at DESC.
func (q *Queries) ListLots(ctx context.Context, tenantID pgtype.UUID) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listLots, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.Sku,
			&i.Quantity,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LotNotes,
			&i.ManufacturedAt,
			&i.BestBeforeDate,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsBySkuForTenant = `-- name: ListLotsBySkuForTenant :many
SELECT id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
       lot_notes, manufactured_at, best_before_date, tenant_id
FROM lots
WHERE tenant_id = $1 AND sku = $2
ORDER BY created_at DESC
`

type ListLotsBySkuForTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Sku      string      `json:"sku"`
}

// Tenant-scoped lookup by SKU; replaces the un-scoped ListLotsBySku for HTTP callers.
func (q *Queries) ListLotsBySkuForTenant(ctx context.Context, arg ListLotsBySkuForTenantParams) ([]Lot, error) {
	rows, err := q.db.Query(ctx, listLotsBySkuForTenant, arg.TenantID, arg.Sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lot{}
	for rows.Next() {
		var i Lot
		if err := rows.Scan(
			&i.ID,
			&i.LotNumber,
			&i.Sku,
			&i.Quantity,
			&i.ExpirationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LotNotes,
			&i.ManufacturedAt,
			&i.BestBeforeDate,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLot = `-- name: UpdateLot :one
UPDATE lots
SET
    lot_number = $3,
    sku = $4,
    quantity = $5,
    expiration_date = $6,
    status = $7,
    lot_notes = $8,
    manufactured_at = $9,
    best_before_date = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, lot_number, sku, quantity, expiration_date, created_at, updated_at, status,
          lot_notes, manufactured_at, best_before_date, tenant_id
`

type UpdateLotParams struct {
	ID             string           `json:"id"`
	TenantID       pgtype.UUID      `json:"tenant_id"`
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	Status         string           `json:"status"`
	LotNotes       pgtype.Text      `json:"lot_notes"`
	ManufacturedAt pgtype.Date      `json:"manufactured_at"`
	BestBeforeDate pgtype.Date      `json:"best_before_date"`
}

// Tenant guard prevents cross-tenant updates (S3.5 W2-B).
func (q *Queries) UpdateLot(ctx context.Context, arg UpdateLotParams) (Lot, error) {
	row := q.db.QueryRow(ctx, updateLot,
		arg.ID,
		arg.TenantID,
		arg.LotNumber,
		arg.Sku,
		arg.Quantity,
		arg.ExpirationDate,
		arg.Status,
		arg.LotNotes,
		arg.ManufacturedAt,
		arg.BestBeforeDate,
	)
	var i Lot
	err := row.Scan(
		&i.ID,
		&i.LotNumber,
		&i.Sku,
		&i.Quantity,
		&i.ExpirationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LotNotes,
		&i.ManufacturedAt,
		&i.BestBeforeDate,
		&i.TenantID,
	)
	return i, err
}
