// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Adjustment struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Location           string           `json:"location"`
	PreviousQuantity   int32            `json:"previous_quantity"`
	AdjustmentQuantity int32            `json:"adjustment_quantity"`
	NewQuantity        int32            `json:"new_quantity"`
	Reason             string           `json:"reason"`
	Notes              pgtype.Text      `json:"notes"`
	UserID             string           `json:"user_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	AdjustmentType     string           `json:"adjustment_type"`
	TenantID           pgtype.UUID      `json:"tenant_id"`
}

// Reason codes for stock adjustments; direction determines add (inbound) or subtract (outbound).
type AdjustmentReasonCode struct {
	ID           string           `json:"id"`
	Code         string           `json:"code"`
	Name         string           `json:"name"`
	Direction    string           `json:"direction"`
	IsSystem     bool             `json:"is_system"`
	DisplayOrder int32            `json:"display_order"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Article struct {
	ID              string           `json:"id"`
	Sku             string           `json:"sku"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	UnitPrice       pgtype.Numeric   `json:"unit_price"`
	Presentation    string           `json:"presentation"`
	TrackByLot      bool             `json:"track_by_lot"`
	TrackBySerial   bool             `json:"track_by_serial"`
	TrackExpiration bool             `json:"track_expiration"`
	MinQuantity     pgtype.Int4      `json:"min_quantity"`
	MaxQuantity     pgtype.Int4      `json:"max_quantity"`
	ImageUrl        pgtype.Text      `json:"image_url"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	// WMS rotation rule: fifo = oldest first, fefo = earliest expiry first (requires track_expiration)
	RotationStrategy   string         `json:"rotation_strategy"`
	CategoryID         pgtype.Text    `json:"category_id"`
	ShelfLifeInDays    pgtype.Int4    `json:"shelf_life_in_days"`
	SafetyStock        pgtype.Numeric `json:"safety_stock"`
	BatchNumberSeries  pgtype.Text    `json:"batch_number_series"`
	SerialNumberSeries pgtype.Text    `json:"serial_number_series"`
	MinOrderQty        pgtype.Numeric `json:"min_order_qty"`
	DefaultLocationID  pgtype.Text    `json:"default_location_id"`
	ReceivingNotes     pgtype.Text    `json:"receiving_notes"`
	ShippingNotes      pgtype.Text    `json:"shipping_notes"`
	TenantID           pgtype.UUID    `json:"tenant_id"`
}

type ArticleSupplier struct {
	ID           string             `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ArticleSku   string             `json:"article_sku"`
	SupplierID   string             `json:"supplier_id"`
	IsPreferred  bool               `json:"is_preferred"`
	LeadTimeDays pgtype.Int4        `json:"lead_time_days"`
	UnitCost     pgtype.Numeric     `json:"unit_cost"`
	SupplierSku  pgtype.Text        `json:"supplier_sku"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID           string      `json:"id"`
	UserID       pgtype.Text `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	OldValue     []byte      `json:"old_value"`
	NewValue     []byte      `json:"new_value"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Backorder struct {
	ID                     string             `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	OriginalSalesOrderID   string             `json:"original_sales_order_id"`
	ArticleSku             string             `json:"article_sku"`
	RemainingQty           pgtype.Numeric     `json:"remaining_qty"`
	Status                 string             `json:"status"`
	GeneratedPickingTaskID pgtype.Text        `json:"generated_picking_task_id"`
	FulfilledAt            pgtype.Timestamptz `json:"fulfilled_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type Badge struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Emoji       string           `json:"emoji"`
	RuleType    string           `json:"rule_type"`
	Criteria    json.RawMessage  `json:"criteria"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Category struct {
	ID        string      `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.Text `json:"parent_id"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Client struct {
	ID        string      `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Type      string      `json:"type"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Address   pgtype.Text `json:"address"`
	TaxID     pgtype.Text `json:"tax_id"`
	Notes     pgtype.Text `json:"notes"`
	IsActive  bool        `json:"is_active"`
	CreatedBy pgtype.Text `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type DeliveryNote struct {
	ID             string             `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	DnNumber       string             `json:"dn_number"`
	SalesOrderID   string             `json:"sales_order_id"`
	PickingTaskID  pgtype.Text        `json:"picking_task_id"`
	CustomerID     string             `json:"customer_id"`
	TotalItems     int32              `json:"total_items"`
	PdfUrl         pgtype.Text        `json:"pdf_url"`
	PdfGeneratedAt pgtype.Timestamptz `json:"pdf_generated_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	SignedBy       pgtype.Text        `json:"signed_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type DeliveryNoteItem struct {
	ID             string         `json:"id"`
	DeliveryNoteID string         `json:"delivery_note_id"`
	ArticleSku     string         `json:"article_sku"`
	Qty            pgtype.Numeric `json:"qty"`
	LotNumbers     []string       `json:"lot_numbers"`
	Notes          pgtype.Text    `json:"notes"`
	CreatedAt      time.Time      `json:"created_at"`
}

type DemoDataSeed struct {
	ID       string      `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	SeedName string      `json:"seed_name"`
	SeededAt time.Time   `json:"seeded_at"`
	Metadata []byte      `json:"metadata"`
}

type Inventory struct {
	ID           string           `json:"id"`
	Sku          string           `json:"sku"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Location     string           `json:"location"`
	Quantity     pgtype.Numeric   `json:"quantity"`
	Status       string           `json:"status"`
	Presentation string           `json:"presentation"`
	UnitPrice    pgtype.Numeric   `json:"unit_price"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	ReservedQty  pgtype.Numeric   `json:"reserved_qty"`
}

// Cycle/physical count sheets (mobile-driven). variance_qty on each line drives auto-adjustment on submit.
type InventoryCount struct {
	ID           string           `json:"id"`
	Code         string           `json:"code"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Status       string           `json:"status"`
	ScheduledFor pgtype.Timestamp `json:"scheduled_for"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
	SubmittedAt  pgtype.Timestamp `json:"submitted_at"`
	SubmittedBy  pgtype.Text      `json:"submitted_by"`
	AdjustmentID pgtype.Text      `json:"adjustment_id"`
	CreatedBy    string           `json:"created_by"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type InventoryCountLine struct {
	ID          string         `json:"id"`
	CountID     string         `json:"count_id"`
	LocationID  string         `json:"location_id"`
	Sku         string         `json:"sku"`
	Lot         pgtype.Text    `json:"lot"`
	Serial      pgtype.Text    `json:"serial"`
	ExpectedQty pgtype.Numeric `json:"expected_qty"`
	ScannedQty  pgtype.Numeric `json:"scanned_qty"`
	// scanned_qty - expected_qty; positive = stock found extra, negative = stock missing.
	VarianceQty pgtype.Numeric   `json:"variance_qty"`
	Note        pgtype.Text      `json:"note"`
	ScannedBy   string           `json:"scanned_by"`
	ScannedAt   pgtype.Timestamp `json:"scanned_at"`
}

type InventoryCountLocation struct {
	ID         string      `json:"id"`
	CountID    string      `json:"count_id"`
	LocationID string      `json:"location_id"`
	Status     string      `json:"status"`
	AssignedTo pgtype.Text `json:"assigned_to"`
}

type InventoryLot struct {
	ID          string           `json:"id"`
	InventoryID string           `json:"inventory_id"`
	LotID       string           `json:"lot_id"`
	Quantity    pgtype.Numeric   `json:"quantity"`
	Location    string           `json:"location"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	TenantID    pgtype.UUID      `json:"tenant_id"`
}

type InventoryMovement struct {
	ID             string           `json:"id"`
	Sku            string           `json:"sku"`
	Location       string           `json:"location"`
	MovementType   string           `json:"movement_type"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	RemainingStock pgtype.Numeric   `json:"remaining_stock"`
	Reason         pgtype.Text      `json:"reason"`
	CreatedBy      string           `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	ReferenceType  pgtype.Text      `json:"reference_type"`
	ReferenceID    pgtype.Text      `json:"reference_id"`
	LotID          pgtype.Text      `json:"lot_id"`
	SerialID       pgtype.Text      `json:"serial_id"`
	UnitCost       pgtype.Numeric   `json:"unit_cost"`
	BeforeQty      pgtype.Numeric   `json:"before_qty"`
	AfterQty       pgtype.Numeric   `json:"after_qty"`
	UserID         pgtype.Text      `json:"user_id"`
}

type InventorySerial struct {
	ID          string           `json:"id"`
	InventoryID string           `json:"inventory_id"`
	SerialID    string           `json:"serial_id"`
	Location    string           `json:"location"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Location struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	// When true, location is used as dock, loading bay, or exit point in WMS.
	IsWayOut bool        `json:"is_way_out"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Location type catalog (Pallet, Shelf, Bin, etc.); used by locations.type as code reference
type LocationType struct {
	ID        string           `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	SortOrder int32            `json:"sort_order"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Lot struct {
	ID             string           `json:"id"`
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Status         string           `json:"status"`
	LotNotes       pgtype.Text      `json:"lot_notes"`
	ManufacturedAt pgtype.Date      `json:"manufactured_at"`
	BestBeforeDate pgtype.Date      `json:"best_before_date"`
	TenantID       pgtype.UUID      `json:"tenant_id"`
}

type Notification struct {
	ID           string             `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       string             `json:"user_id"`
	EventType    string             `json:"event_type"`
	Title        string             `json:"title"`
	Body         pgtype.Text        `json:"body"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Channels     string             `json:"channels"`
	IsRead       bool               `json:"is_read"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	SentEmailAt  pgtype.Timestamptz `json:"sent_email_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type NotificationPreference struct {
	UserID    string      `json:"user_id"`
	EventType string      `json:"event_type"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	InApp     bool        `json:"in_app"`
	Email     bool        `json:"email"`
	Push      bool        `json:"push"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type PickingTask struct {
	ID                string           `json:"id"`
	TaskID            string           `json:"task_id"`
	OrderNumber       string           `json:"order_number"`
	CreatedBy         string           `json:"created_by"`
	AssignedTo        pgtype.Text      `json:"assigned_to"`
	Status            string           `json:"status"`
	Priority          string           `json:"priority"`
	Notes             pgtype.Text      `json:"notes"`
	Items             json.RawMessage  `json:"items"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CompletedAt       pgtype.Timestamp `json:"completed_at"`
	CustomerID        pgtype.Text      `json:"customer_id"`
	TenantID          pgtype.UUID      `json:"tenant_id"`
	SalesOrderID      pgtype.Text      `json:"sales_order_id"`
	SourceBackorderID pgtype.Text      `json:"source_backorder_id"`
}

type Presentation struct {
	PresentationID string      `json:"presentation_id"`
	Description    pgtype.Text `json:"description"`
}

// Conversion factors between presentation types: 1 unit of from = conversion_factor units of to (e.g. 1 PALLET = 20 CAJA).
type PresentationConversion struct {
	ID                     string           `json:"id"`
	FromPresentationTypeID string           `json:"from_presentation_type_id"`
	ToPresentationTypeID   string           `json:"to_presentation_type_id"`
	ConversionFactor       pgtype.Numeric   `json:"conversion_factor"`
	IsActive               bool             `json:"is_active"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}

// Presentation type catalog (Unidad, Caja, Pallet, Paquete, etc.); used by articles.presentation as code reference
type PresentationType struct {
	ID        string           `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	SortOrder int32            `json:"sort_order"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type PurchaseOrder struct {
	ID              string             `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	PoNumber        string             `json:"po_number"`
	SupplierID      string             `json:"supplier_id"`
	Status          string             `json:"status"`
	ExpectedDate    pgtype.Date        `json:"expected_date"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       pgtype.Text        `json:"created_by"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	ReceivingTaskID pgtype.Text        `json:"receiving_task_id"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type PurchaseOrderItem struct {
	ID              string         `json:"id"`
	PurchaseOrderID string         `json:"purchase_order_id"`
	ArticleSku      string         `json:"article_sku"`
	ExpectedQty     pgtype.Numeric `json:"expected_qty"`
	ReceivedQty     pgtype.Numeric `json:"received_qty"`
	RejectedQty     pgtype.Numeric `json:"rejected_qty"`
	UnitCost        pgtype.Numeric `json:"unit_cost"`
	Discrepancy     pgtype.Numeric `json:"discrepancy"`
	Notes           pgtype.Text    `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ReceivingTask struct {
	ID              string           `json:"id"`
	TaskID          string           `json:"task_id"`
	InboundNumber   string           `json:"inbound_number"`
	CreatedBy       string           `json:"created_by"`
	AssignedTo      pgtype.Text      `json:"assigned_to"`
	Status          string           `json:"status"`
	Priority        string           `json:"priority"`
	Notes           pgtype.Text      `json:"notes"`
	Items           json.RawMessage  `json:"items"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CompletedAt     pgtype.Timestamp `json:"completed_at"`
	SupplierID      pgtype.Text      `json:"supplier_id"`
	VendorRef       pgtype.Text      `json:"vendor_ref"`
	TrackingNumber  pgtype.Text      `json:"tracking_number"`
	ReceptionMethod pgtype.Text      `json:"reception_method"`
	Incoterms       pgtype.Text      `json:"incoterms"`
	TenantID        pgtype.UUID      `json:"tenant_id"`
	PurchaseOrderID pgtype.Text      `json:"purchase_order_id"`
}

// RBAC roles; name is the stable identifier (Admin, Operator, Viewer).
type Role struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	IsActive    bool            `json:"is_active"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type SalesOrder struct {
	ID            string             `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	SoNumber      string             `json:"so_number"`
	CustomerID    string             `json:"customer_id"`
	Status        string             `json:"status"`
	ExpectedDate  pgtype.Date        `json:"expected_date"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Text        `json:"created_by"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	PickingTaskID pgtype.Text        `json:"picking_task_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type SalesOrderItem struct {
	ID           string         `json:"id"`
	SalesOrderID string         `json:"sales_order_id"`
	ArticleSku   string         `json:"article_sku"`
	ExpectedQty  pgtype.Numeric `json:"expected_qty"`
	PickedQty    pgtype.Numeric `json:"picked_qty"`
	UnitPrice    pgtype.Numeric `json:"unit_price"`
	Notes        pgtype.Text    `json:"notes"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Serial struct {
	ID           string           `json:"id"`
	SerialNumber string           `json:"serial_number"`
	Sku          string           `json:"sku"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	TenantID     pgtype.UUID      `json:"tenant_id"`
}

// Sessions table for managing user authentication sessions
type Session struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	SessionTypeID string `json:"session_type_id"`
	// Hash of access token
	TokenHash string `json:"token_hash"`
	// Hash of refresh token
	RefreshTokenHash pgtype.Text `json:"refresh_token_hash"`
	UserAgent        pgtype.Text `json:"user_agent"`
	ClientIp         pgtype.Text `json:"client_ip"`
	// IP address of the client (INET type)
	IpAddress  *netip.Addr `json:"ip_address"`
	DeviceInfo []byte      `json:"device_info"`
	IsActive   pgtype.Bool `json:"is_active"`
	// Session expiry
	ExpiresAt      time.Time          `json:"expires_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedBy      pgtype.Text        `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// Session types for different session configurations
type SessionType struct {
	// Unique identifier for the session type
	ID string `json:"id"`
	// Name of the session type (must be unique)
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	// Default duration for this session type in minutes
	DurationMinutes int32              `json:"duration_minutes"`
	IsActive        pgtype.Bool        `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       pgtype.Text        `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type SignupToken struct {
	ID               string             `json:"id"`
	Email            string             `json:"email"`
	TenantName       string             `json:"tenant_name"`
	TenantSlug       string             `json:"tenant_slug"`
	Token            string             `json:"token"`
	ExpiresAt        time.Time          `json:"expires_at"`
	UsedAt           pgtype.Timestamptz `json:"used_at"`
	CreatedAt        time.Time          `json:"created_at"`
	AdminName        string             `json:"admin_name"`
	AdminPasswordEnc string             `json:"admin_password_enc"`
	SeedDemoData     bool               `json:"seed_demo_data"`
}

type StockAlert struct {
	ID                    string           `json:"id"`
	Sku                   string           `json:"sku"`
	AlertType             string           `json:"alert_type"`
	CurrentStock          int32            `json:"current_stock"`
	RecommendedStock      int32            `json:"recommended_stock"`
	AlertLevel            string           `json:"alert_level"`
	PredictedStockOutDays pgtype.Int4      `json:"predicted_stock_out_days"`
	Message               string           `json:"message"`
	IsResolved            bool             `json:"is_resolved"`
	LotNumber             pgtype.Text      `json:"lot_number"`
	ExpirationDate        pgtype.Timestamp `json:"expiration_date"`
	DaysToExpiration      pgtype.Int4      `json:"days_to_expiration"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	ResolvedAt            pgtype.Timestamp `json:"resolved_at"`
	TenantID              pgtype.UUID      `json:"tenant_id"`
}

type StockSetting struct {
	TenantID                  pgtype.UUID    `json:"tenant_id"`
	ValuationMethod           string         `json:"valuation_method"`
	PickBatchBasedOn          string         `json:"pick_batch_based_on"`
	OverReceiptAllowancePct   pgtype.Numeric `json:"over_receipt_allowance_pct"`
	OverDeliveryAllowancePct  pgtype.Numeric `json:"over_delivery_allowance_pct"`
	OverPickingAllowancePct   pgtype.Numeric `json:"over_picking_allowance_pct"`
	AutoReserveStock          bool           `json:"auto_reserve_stock"`
	AllowPartialReservation   bool           `json:"allow_partial_reservation"`
	ExpiryAlertDays           int32          `json:"expiry_alert_days"`
	AutoCreateMaterialRequest bool           `json:"auto_create_material_request"`
	PartialDeliveryPolicy     string         `json:"partial_delivery_policy"`
	UpdatedAt                 time.Time      `json:"updated_at"`
}

type StockTransfer struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
	// Optional dock or loading bay at destination for receiving (WMS).
	DockLocation pgtype.Text `json:"dock_location"`
}

type StockTransferLine struct {
	ID              string           `json:"id"`
	StockTransferID string           `json:"stock_transfer_id"`
	Sku             string           `json:"sku"`
	Quantity        pgtype.Numeric   `json:"quantity"`
	Presentation    pgtype.Text      `json:"presentation"`
	LineStatus      string           `json:"line_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type StripeWebhookEvent struct {
	EventID     string    `json:"event_id"`
	EventType   string    `json:"event_type"`
	ProcessedAt time.Time `json:"processed_at"`
	RawEvent    []byte    `json:"raw_event"`
}

type Subscription struct {
	ID                   string             `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	Plan                 string             `json:"plan"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	TrialEnd             pgtype.Timestamptz `json:"trial_end"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type Tenant struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Email          string             `json:"email"`
	Status         string             `json:"status"`
	SignupAt       time.Time          `json:"signup_at"`
	TrialStartedAt time.Time          `json:"trial_started_at"`
	TrialEndsAt    time.Time          `json:"trial_ends_at"`
	IsActive       bool               `json:"is_active"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// User identity and account; session and token data are in sessions table.
type User struct {
	ID string `json:"id"`
	// Full name of the user (display)
	Name            string      `json:"name"`
	Email           pgtype.Text `json:"email"`
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	Password        pgtype.Text `json:"password"`
	RoleID          string      `json:"role_id"`
	IsActive        bool        `json:"is_active"`
	// Whether the email has been verified
	EmailVerified pgtype.Bool `json:"email_verified"`
	// When the email was verified
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	// User id who last updated (set via app.current_user_id)
	UpdatedBy pgtype.Text `json:"updated_by"`
	// Soft delete; NULL = active
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
}

type UserBadge struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	BadgeID   string           `json:"badge_id"`
	AwardedAt pgtype.Timestamp `json:"awarded_at"`
}

// Per-user preferences (theme, language, notifications, privacy).
type UserPreference struct {
	ID                     string      `json:"id"`
	UserID                 string      `json:"user_id"`
	Theme                  string      `json:"theme"`
	Language               string      `json:"language"`
	EmailNotifications     bool        `json:"email_notifications"`
	PushNotifications      bool        `json:"push_notifications"`
	MarketingNotifications bool        `json:"marketing_notifications"`
	ProfileVisibility      string      `json:"profile_visibility"`
	DataSharing            bool        `json:"data_sharing"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedBy              pgtype.Text `json:"updated_by"`
	UpdatedAt              time.Time   `json:"updated_at"`
}

type UserStat struct {
	ID                      string           `json:"id"`
	UserID                  string           `json:"user_id"`
	ReceivingTasksCompleted pgtype.Int4      `json:"receiving_tasks_completed"`
	PickingTasksCompleted   pgtype.Int4      `json:"picking_tasks_completed"`
	AvgPickTime             pgtype.Int4      `json:"avg_pick_time"`
	PickAccuracy            pgtype.Int4      `json:"pick_accuracy"`
	TotalPickingTime        pgtype.Int4      `json:"total_picking_time"`
	CorrectPicks            pgtype.Int4      `json:"correct_picks"`
	TotalPicks              pgtype.Int4      `json:"total_picks"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}
