// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Adjustment struct {
	ID                 string           `json:"id"`
	Sku                string           `json:"sku"`
	Location           string           `json:"location"`
	PreviousQuantity   int32            `json:"previous_quantity"`
	AdjustmentQuantity int32            `json:"adjustment_quantity"`
	NewQuantity        int32            `json:"new_quantity"`
	Reason             string           `json:"reason"`
	Notes              pgtype.Text      `json:"notes"`
	UserID             string           `json:"user_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Article struct {
	ID              string           `json:"id"`
	Sku             string           `json:"sku"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	UnitPrice       pgtype.Numeric   `json:"unit_price"`
	Presentation    string           `json:"presentation"`
	TrackByLot      bool             `json:"track_by_lot"`
	TrackBySerial   bool             `json:"track_by_serial"`
	TrackExpiration bool             `json:"track_expiration"`
	MinQuantity     pgtype.Int4      `json:"min_quantity"`
	MaxQuantity     pgtype.Int4      `json:"max_quantity"`
	ImageUrl        pgtype.Text      `json:"image_url"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type AuditLog struct {
	ID           string      `json:"id"`
	UserID       pgtype.Text `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	OldValue     []byte      `json:"old_value"`
	NewValue     []byte      `json:"new_value"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Badge struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Emoji       string           `json:"emoji"`
	RuleType    string           `json:"rule_type"`
	Criteria    json.RawMessage  `json:"criteria"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Inventory struct {
	ID           string           `json:"id"`
	Sku          string           `json:"sku"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Location     string           `json:"location"`
	Quantity     pgtype.Numeric   `json:"quantity"`
	Status       string           `json:"status"`
	Presentation string           `json:"presentation"`
	UnitPrice    pgtype.Numeric   `json:"unit_price"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type InventoryLot struct {
	ID          string           `json:"id"`
	InventoryID string           `json:"inventory_id"`
	LotID       string           `json:"lot_id"`
	Quantity    pgtype.Numeric   `json:"quantity"`
	Location    string           `json:"location"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type InventoryMovement struct {
	ID             string           `json:"id"`
	Sku            string           `json:"sku"`
	Location       string           `json:"location"`
	MovementType   string           `json:"movement_type"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	RemainingStock pgtype.Numeric   `json:"remaining_stock"`
	Reason         pgtype.Text      `json:"reason"`
	CreatedBy      string           `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type InventorySerial struct {
	ID          string           `json:"id"`
	InventoryID string           `json:"inventory_id"`
	SerialID    string           `json:"serial_id"`
	Location    string           `json:"location"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Location struct {
	ID           string           `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// Location type catalog (Pallet, Shelf, Bin, etc.); used by locations.type as code reference
type LocationType struct {
	ID        string           `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	SortOrder int32            `json:"sort_order"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Lot struct {
	ID             string           `json:"id"`
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Status         string           `json:"status"`
}

type PickingTask struct {
	ID          string           `json:"id"`
	TaskID      string           `json:"task_id"`
	OrderNumber string           `json:"order_number"`
	CreatedBy   string           `json:"created_by"`
	AssignedTo  pgtype.Text      `json:"assigned_to"`
	Status      string           `json:"status"`
	Priority    string           `json:"priority"`
	Notes       pgtype.Text      `json:"notes"`
	Items       json.RawMessage  `json:"items"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type Presentation struct {
	PresentationID string      `json:"presentation_id"`
	Description    pgtype.Text `json:"description"`
}

// Conversion factors between presentation types: 1 unit of from = conversion_factor units of to (e.g. 1 PALLET = 20 CAJA).
type PresentationConversion struct {
	ID                     string           `json:"id"`
	FromPresentationTypeID string           `json:"from_presentation_type_id"`
	ToPresentationTypeID   string           `json:"to_presentation_type_id"`
	ConversionFactor       pgtype.Numeric   `json:"conversion_factor"`
	IsActive               bool             `json:"is_active"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}

// Presentation type catalog (Unidad, Caja, Pallet, Paquete, etc.); used by articles.presentation as code reference
type PresentationType struct {
	ID        string           `json:"id"`
	Code      string           `json:"code"`
	Name      string           `json:"name"`
	SortOrder int32            `json:"sort_order"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ReceivingTask struct {
	ID            string           `json:"id"`
	TaskID        string           `json:"task_id"`
	InboundNumber string           `json:"inbound_number"`
	CreatedBy     string           `json:"created_by"`
	AssignedTo    pgtype.Text      `json:"assigned_to"`
	Status        string           `json:"status"`
	Priority      string           `json:"priority"`
	Notes         pgtype.Text      `json:"notes"`
	Items         json.RawMessage  `json:"items"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
}

// RBAC roles; name is the stable identifier (Admin, Operator, Viewer).
type Role struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	IsActive    bool            `json:"is_active"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Serial struct {
	ID           string           `json:"id"`
	SerialNumber string           `json:"serial_number"`
	Sku          string           `json:"sku"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

// Sessions table for managing user authentication sessions
type Session struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	SessionTypeID string `json:"session_type_id"`
	// Hash of access token
	TokenHash string `json:"token_hash"`
	// Hash of refresh token
	RefreshTokenHash pgtype.Text `json:"refresh_token_hash"`
	UserAgent        pgtype.Text `json:"user_agent"`
	ClientIp         pgtype.Text `json:"client_ip"`
	// IP address of the client (INET type)
	IpAddress  *netip.Addr `json:"ip_address"`
	DeviceInfo []byte      `json:"device_info"`
	IsActive   pgtype.Bool `json:"is_active"`
	// Session expiry
	ExpiresAt      time.Time          `json:"expires_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedBy      pgtype.Text        `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// Session types for different session configurations
type SessionType struct {
	// Unique identifier for the session type
	ID string `json:"id"`
	// Name of the session type (must be unique)
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	// Default duration for this session type in minutes
	DurationMinutes int32              `json:"duration_minutes"`
	IsActive        pgtype.Bool        `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       pgtype.Text        `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type StockAlert struct {
	ID                    string           `json:"id"`
	Sku                   string           `json:"sku"`
	AlertType             string           `json:"alert_type"`
	CurrentStock          int32            `json:"current_stock"`
	RecommendedStock      int32            `json:"recommended_stock"`
	AlertLevel            string           `json:"alert_level"`
	PredictedStockOutDays pgtype.Int4      `json:"predicted_stock_out_days"`
	Message               string           `json:"message"`
	IsResolved            bool             `json:"is_resolved"`
	LotNumber             pgtype.Text      `json:"lot_number"`
	ExpirationDate        pgtype.Timestamp `json:"expiration_date"`
	DaysToExpiration      pgtype.Int4      `json:"days_to_expiration"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	ResolvedAt            pgtype.Timestamp `json:"resolved_at"`
}

type StockTransfer struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

type StockTransferLine struct {
	ID              string           `json:"id"`
	StockTransferID string           `json:"stock_transfer_id"`
	Sku             string           `json:"sku"`
	Quantity        pgtype.Numeric   `json:"quantity"`
	Presentation    pgtype.Text      `json:"presentation"`
	LineStatus      string           `json:"line_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

// User identity and account; session and token data are in sessions table.
type User struct {
	ID string `json:"id"`
	// Full name of the user (display)
	Name            string      `json:"name"`
	Email           pgtype.Text `json:"email"`
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	Password        pgtype.Text `json:"password"`
	RoleID          string      `json:"role_id"`
	IsActive        bool        `json:"is_active"`
	// Whether the email has been verified
	EmailVerified pgtype.Bool `json:"email_verified"`
	// When the email was verified
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	// User id who last updated (set via app.current_user_id)
	UpdatedBy pgtype.Text `json:"updated_by"`
	// Soft delete; NULL = active
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserBadge struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	BadgeID   string           `json:"badge_id"`
	AwardedAt pgtype.Timestamp `json:"awarded_at"`
}

// Per-user preferences (theme, language, notifications, privacy).
type UserPreference struct {
	ID                     string      `json:"id"`
	UserID                 string      `json:"user_id"`
	Theme                  string      `json:"theme"`
	Language               string      `json:"language"`
	EmailNotifications     bool        `json:"email_notifications"`
	PushNotifications      bool        `json:"push_notifications"`
	MarketingNotifications bool        `json:"marketing_notifications"`
	ProfileVisibility      string      `json:"profile_visibility"`
	DataSharing            bool        `json:"data_sharing"`
	CreatedAt              time.Time   `json:"created_at"`
	UpdatedBy              pgtype.Text `json:"updated_by"`
	UpdatedAt              time.Time   `json:"updated_at"`
}

type UserStat struct {
	ID                      string           `json:"id"`
	UserID                  string           `json:"user_id"`
	ReceivingTasksCompleted pgtype.Int4      `json:"receiving_tasks_completed"`
	PickingTasksCompleted   pgtype.Int4      `json:"picking_tasks_completed"`
	AvgPickTime             pgtype.Int4      `json:"avg_pick_time"`
	PickAccuracy            pgtype.Int4      `json:"pick_accuracy"`
	TotalPickingTime        pgtype.Int4      `json:"total_picking_time"`
	CorrectPicks            pgtype.Int4      `json:"correct_picks"`
	TotalPicks              pgtype.Int4      `json:"total_picks"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}
