// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Adjustment struct {
	ID                 int32            `json:"id"`
	Sku                string           `json:"sku"`
	Location           string           `json:"location"`
	PreviousQuantity   int32            `json:"previous_quantity"`
	AdjustmentQuantity int32            `json:"adjustment_quantity"`
	NewQuantity        int32            `json:"new_quantity"`
	Reason             string           `json:"reason"`
	Notes              pgtype.Text      `json:"notes"`
	UserID             string           `json:"user_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type Article struct {
	ID              int32            `json:"id"`
	Sku             string           `json:"sku"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	UnitPrice       pgtype.Numeric   `json:"unit_price"`
	Presentation    string           `json:"presentation"`
	TrackByLot      bool             `json:"track_by_lot"`
	TrackBySerial   bool             `json:"track_by_serial"`
	TrackExpiration bool             `json:"track_expiration"`
	MinQuantity     pgtype.Int4      `json:"min_quantity"`
	MaxQuantity     pgtype.Int4      `json:"max_quantity"`
	ImageUrl        pgtype.Text      `json:"image_url"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

// Audit log for tracking user actions (create, update, delete)
type AuditLog struct {
	ID     string      `json:"id"`
	UserID pgtype.Text `json:"user_id"`
	// create, update, delete, login, logout
	Action string `json:"action"`
	// article, lot, location, serial, etc.
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	OldValue     []byte      `json:"old_value"`
	NewValue     []byte      `json:"new_value"`
	IpAddress    pgtype.Text `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Badge struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Emoji       string           `json:"emoji"`
	RuleType    string           `json:"rule_type"`
	Criteria    json.RawMessage  `json:"criteria"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Inventory struct {
	ID           int32            `json:"id"`
	Sku          string           `json:"sku"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	Location     string           `json:"location"`
	Quantity     pgtype.Numeric   `json:"quantity"`
	Status       string           `json:"status"`
	Presentation string           `json:"presentation"`
	UnitPrice    pgtype.Numeric   `json:"unit_price"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type InventoryLot struct {
	ID          int32            `json:"id"`
	InventoryID int32            `json:"inventory_id"`
	LotID       int32            `json:"lot_id"`
	Quantity    pgtype.Numeric   `json:"quantity"`
	Location    string           `json:"location"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type InventoryMovement struct {
	ID             int32            `json:"id"`
	Sku            string           `json:"sku"`
	Location       string           `json:"location"`
	MovementType   string           `json:"movement_type"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	RemainingStock pgtype.Numeric   `json:"remaining_stock"`
	Reason         pgtype.Text      `json:"reason"`
	CreatedBy      string           `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type InventorySerial struct {
	ID          int32            `json:"id"`
	InventoryID int32            `json:"inventory_id"`
	SerialID    int32            `json:"serial_id"`
	Location    string           `json:"location"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Location struct {
	ID           int32            `json:"id"`
	LocationCode string           `json:"location_code"`
	Description  pgtype.Text      `json:"description"`
	Zone         pgtype.Text      `json:"zone"`
	Type         string           `json:"type"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Lot struct {
	ID             int32            `json:"id"`
	LotNumber      string           `json:"lot_number"`
	Sku            string           `json:"sku"`
	Quantity       pgtype.Numeric   `json:"quantity"`
	ExpirationDate pgtype.Timestamp `json:"expiration_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Status         string           `json:"status"`
}

type PickingTask struct {
	ID          int32            `json:"id"`
	TaskID      string           `json:"task_id"`
	OrderNumber string           `json:"order_number"`
	CreatedBy   string           `json:"created_by"`
	AssignedTo  pgtype.Text      `json:"assigned_to"`
	Status      string           `json:"status"`
	Priority    string           `json:"priority"`
	Notes       pgtype.Text      `json:"notes"`
	Items       json.RawMessage  `json:"items"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type Presentation struct {
	PresentationID string      `json:"presentation_id"`
	Description    pgtype.Text `json:"description"`
}

type ReceivingTask struct {
	ID            int32            `json:"id"`
	TaskID        string           `json:"task_id"`
	InboundNumber string           `json:"inbound_number"`
	CreatedBy     string           `json:"created_by"`
	AssignedTo    pgtype.Text      `json:"assigned_to"`
	Status        string           `json:"status"`
	Priority      string           `json:"priority"`
	Notes         pgtype.Text      `json:"notes"`
	Items         json.RawMessage  `json:"items"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
}

type Serial struct {
	ID           int32            `json:"id"`
	SerialNumber string           `json:"serial_number"`
	Sku          string           `json:"sku"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	Sid    string           `json:"sid"`
	Sess   json.RawMessage  `json:"sess"`
	Expire pgtype.Timestamp `json:"expire"`
}

type StockAlert struct {
	ID                    int32            `json:"id"`
	Sku                   string           `json:"sku"`
	AlertType             string           `json:"alert_type"`
	CurrentStock          int32            `json:"current_stock"`
	RecommendedStock      int32            `json:"recommended_stock"`
	AlertLevel            string           `json:"alert_level"`
	PredictedStockOutDays pgtype.Int4      `json:"predicted_stock_out_days"`
	Message               string           `json:"message"`
	IsResolved            bool             `json:"is_resolved"`
	LotNumber             pgtype.Text      `json:"lot_number"`
	ExpirationDate        pgtype.Timestamp `json:"expiration_date"`
	DaysToExpiration      pgtype.Int4      `json:"days_to_expiration"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	ResolvedAt            pgtype.Timestamp `json:"resolved_at"`
}

type User struct {
	ID                string           `json:"id"`
	Email             pgtype.Text      `json:"email"`
	FirstName         pgtype.Text      `json:"first_name"`
	LastName          pgtype.Text      `json:"last_name"`
	ProfileImageUrl   pgtype.Text      `json:"profile_image_url"`
	Password          pgtype.Text      `json:"password"`
	Role              string           `json:"role"`
	IsActive          bool             `json:"is_active"`
	AuthProvider      pgtype.Text      `json:"auth_provider"`
	ResetToken        pgtype.Text      `json:"reset_token"`
	ResetTokenExpires pgtype.Timestamp `json:"reset_token_expires"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type UserBadge struct {
	ID        int32            `json:"id"`
	UserID    string           `json:"user_id"`
	BadgeID   int32            `json:"badge_id"`
	AwardedAt pgtype.Timestamp `json:"awarded_at"`
}

type UserStat struct {
	ID                      int32            `json:"id"`
	UserID                  string           `json:"user_id"`
	ReceivingTasksCompleted pgtype.Int4      `json:"receiving_tasks_completed"`
	PickingTasksCompleted   pgtype.Int4      `json:"picking_tasks_completed"`
	AvgPickTime             pgtype.Int4      `json:"avg_pick_time"`
	PickAccuracy            pgtype.Int4      `json:"pick_accuracy"`
	TotalPickingTime        pgtype.Int4      `json:"total_picking_time"`
	CorrectPicks            pgtype.Int4      `json:"correct_picks"`
	TotalPicks              pgtype.Int4      `json:"total_picks"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}
