// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: presentation_types.sql

package sqlc

import (
	"context"
)

const createPresentationType = `-- name: CreatePresentationType :one
INSERT INTO presentation_types (code, name, sort_order, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, sort_order, is_active, created_at, updated_at
`

type CreatePresentationTypeParams struct {
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreatePresentationType(ctx context.Context, arg CreatePresentationTypeParams) (PresentationType, error) {
	row := q.db.QueryRow(ctx, createPresentationType,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i PresentationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePresentationType = `-- name: DeletePresentationType :exec
DELETE FROM presentation_types WHERE id = $1
`

func (q *Queries) DeletePresentationType(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePresentationType, id)
	return err
}

const getPresentationTypeByCode = `-- name: GetPresentationTypeByCode :one
SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM presentation_types
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetPresentationTypeByCode(ctx context.Context, code string) (PresentationType, error) {
	row := q.db.QueryRow(ctx, getPresentationTypeByCode, code)
	var i PresentationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresentationTypeByID = `-- name: GetPresentationTypeByID :one
SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM presentation_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPresentationTypeByID(ctx context.Context, id string) (PresentationType, error) {
	row := q.db.QueryRow(ctx, getPresentationTypeByID, id)
	var i PresentationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresentationTypes = `-- name: ListPresentationTypes :many

SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM presentation_types
WHERE is_active = true
ORDER BY sort_order ASC, code ASC
`

// Presentation types CRUD for sqlc. Schema: db/migrations (presentation_types table)
func (q *Queries) ListPresentationTypes(ctx context.Context) ([]PresentationType, error) {
	rows, err := q.db.Query(ctx, listPresentationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationType{}
	for rows.Next() {
		var i PresentationType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentationTypesAdmin = `-- name: ListPresentationTypesAdmin :many
SELECT id, code, name, sort_order, is_active, created_at, updated_at
FROM presentation_types
ORDER BY sort_order ASC, code ASC
`

func (q *Queries) ListPresentationTypesAdmin(ctx context.Context) ([]PresentationType, error) {
	rows, err := q.db.Query(ctx, listPresentationTypesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationType{}
	for rows.Next() {
		var i PresentationType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presentationTypeExistsByCode = `-- name: PresentationTypeExistsByCode :one
SELECT EXISTS(SELECT 1 FROM presentation_types WHERE code = $1) AS exists
`

func (q *Queries) PresentationTypeExistsByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, presentationTypeExistsByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePresentationType = `-- name: UpdatePresentationType :one
UPDATE presentation_types
SET
    code = $2,
    name = $3,
    sort_order = $4,
    is_active = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, name, sort_order, is_active, created_at, updated_at
`

type UpdatePresentationTypeParams struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) UpdatePresentationType(ctx context.Context, arg UpdatePresentationTypeParams) (PresentationType, error) {
	row := q.db.QueryRow(ctx, updatePresentationType,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i PresentationType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
