// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: presentation_conversions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPresentationConversion = `-- name: CreatePresentationConversion :one
INSERT INTO presentation_conversions (from_presentation_type_id, to_presentation_type_id, conversion_factor, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, from_presentation_type_id, to_presentation_type_id, conversion_factor, is_active, created_at, updated_at
`

type CreatePresentationConversionParams struct {
	FromPresentationTypeID string         `json:"from_presentation_type_id"`
	ToPresentationTypeID   string         `json:"to_presentation_type_id"`
	ConversionFactor       pgtype.Numeric `json:"conversion_factor"`
	IsActive               bool           `json:"is_active"`
}

func (q *Queries) CreatePresentationConversion(ctx context.Context, arg CreatePresentationConversionParams) (PresentationConversion, error) {
	row := q.db.QueryRow(ctx, createPresentationConversion,
		arg.FromPresentationTypeID,
		arg.ToPresentationTypeID,
		arg.ConversionFactor,
		arg.IsActive,
	)
	var i PresentationConversion
	err := row.Scan(
		&i.ID,
		&i.FromPresentationTypeID,
		&i.ToPresentationTypeID,
		&i.ConversionFactor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePresentationConversion = `-- name: DeletePresentationConversion :exec
DELETE FROM presentation_conversions WHERE id = $1
`

func (q *Queries) DeletePresentationConversion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePresentationConversion, id)
	return err
}

const getPresentationConversionByFromAndTo = `-- name: GetPresentationConversionByFromAndTo :one
SELECT id, from_presentation_type_id, to_presentation_type_id, conversion_factor, is_active, created_at, updated_at
FROM presentation_conversions
WHERE from_presentation_type_id = $1 AND to_presentation_type_id = $2
LIMIT 1
`

type GetPresentationConversionByFromAndToParams struct {
	FromPresentationTypeID string `json:"from_presentation_type_id"`
	ToPresentationTypeID   string `json:"to_presentation_type_id"`
}

func (q *Queries) GetPresentationConversionByFromAndTo(ctx context.Context, arg GetPresentationConversionByFromAndToParams) (PresentationConversion, error) {
	row := q.db.QueryRow(ctx, getPresentationConversionByFromAndTo, arg.FromPresentationTypeID, arg.ToPresentationTypeID)
	var i PresentationConversion
	err := row.Scan(
		&i.ID,
		&i.FromPresentationTypeID,
		&i.ToPresentationTypeID,
		&i.ConversionFactor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresentationConversionByID = `-- name: GetPresentationConversionByID :one
SELECT id, from_presentation_type_id, to_presentation_type_id, conversion_factor, is_active, created_at, updated_at
FROM presentation_conversions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPresentationConversionByID(ctx context.Context, id string) (PresentationConversion, error) {
	row := q.db.QueryRow(ctx, getPresentationConversionByID, id)
	var i PresentationConversion
	err := row.Scan(
		&i.ID,
		&i.FromPresentationTypeID,
		&i.ToPresentationTypeID,
		&i.ConversionFactor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresentationConversions = `-- name: ListPresentationConversions :many

SELECT pc.id, pc.from_presentation_type_id, pc.to_presentation_type_id, pc.conversion_factor, pc.is_active, pc.created_at, pc.updated_at
FROM presentation_conversions pc
WHERE pc.is_active = true
ORDER BY pc.from_presentation_type_id, pc.to_presentation_type_id
`

// Presentation conversions CRUD. Schema: db/migrations (presentation_conversions table)
func (q *Queries) ListPresentationConversions(ctx context.Context) ([]PresentationConversion, error) {
	rows, err := q.db.Query(ctx, listPresentationConversions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationConversion{}
	for rows.Next() {
		var i PresentationConversion
		if err := rows.Scan(
			&i.ID,
			&i.FromPresentationTypeID,
			&i.ToPresentationTypeID,
			&i.ConversionFactor,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentationConversionsAdmin = `-- name: ListPresentationConversionsAdmin :many
SELECT pc.id, pc.from_presentation_type_id, pc.to_presentation_type_id, pc.conversion_factor, pc.is_active, pc.created_at, pc.updated_at
FROM presentation_conversions pc
ORDER BY pc.from_presentation_type_id, pc.to_presentation_type_id
`

func (q *Queries) ListPresentationConversionsAdmin(ctx context.Context) ([]PresentationConversion, error) {
	rows, err := q.db.Query(ctx, listPresentationConversionsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationConversion{}
	for rows.Next() {
		var i PresentationConversion
		if err := rows.Scan(
			&i.ID,
			&i.FromPresentationTypeID,
			&i.ToPresentationTypeID,
			&i.ConversionFactor,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePresentationConversion = `-- name: UpdatePresentationConversion :one
UPDATE presentation_conversions
SET
    conversion_factor = $2,
    is_active = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, from_presentation_type_id, to_presentation_type_id, conversion_factor, is_active, created_at, updated_at
`

type UpdatePresentationConversionParams struct {
	ID               string         `json:"id"`
	ConversionFactor pgtype.Numeric `json:"conversion_factor"`
	IsActive         bool           `json:"is_active"`
}

func (q *Queries) UpdatePresentationConversion(ctx context.Context, arg UpdatePresentationConversionParams) (PresentationConversion, error) {
	row := q.db.QueryRow(ctx, updatePresentationConversion, arg.ID, arg.ConversionFactor, arg.IsActive)
	var i PresentationConversion
	err := row.Scan(
		&i.ID,
		&i.FromPresentationTypeID,
		&i.ToPresentationTypeID,
		&i.ConversionFactor,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
