// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: presentations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPresentation = `-- name: CreatePresentation :one
INSERT INTO presentations (presentation_id, description)
VALUES ($1, $2)
RETURNING presentation_id, description
`

type CreatePresentationParams struct {
	PresentationID string      `json:"presentation_id"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) CreatePresentation(ctx context.Context, arg CreatePresentationParams) (Presentation, error) {
	row := q.db.QueryRow(ctx, createPresentation, arg.PresentationID, arg.Description)
	var i Presentation
	err := row.Scan(&i.PresentationID, &i.Description)
	return i, err
}

const deletePresentation = `-- name: DeletePresentation :exec
DELETE FROM presentations WHERE presentation_id = $1
`

func (q *Queries) DeletePresentation(ctx context.Context, presentationID string) error {
	_, err := q.db.Exec(ctx, deletePresentation, presentationID)
	return err
}

const getPresentationByID = `-- name: GetPresentationByID :one
SELECT presentation_id, description
FROM presentations
WHERE presentation_id = $1
LIMIT 1
`

func (q *Queries) GetPresentationByID(ctx context.Context, presentationID string) (Presentation, error) {
	row := q.db.QueryRow(ctx, getPresentationByID, presentationID)
	var i Presentation
	err := row.Scan(&i.PresentationID, &i.Description)
	return i, err
}

const listPresentations = `-- name: ListPresentations :many

SELECT presentation_id, description
FROM presentations
ORDER BY description ASC
`

// Presentations CRUD for sqlc
// Schema: db/migrations (presentations table)
func (q *Queries) ListPresentations(ctx context.Context) ([]Presentation, error) {
	rows, err := q.db.Query(ctx, listPresentations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Presentation{}
	for rows.Next() {
		var i Presentation
		if err := rows.Scan(&i.PresentationID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const presentationExistsByID = `-- name: PresentationExistsByID :one
SELECT EXISTS(SELECT 1 FROM presentations WHERE presentation_id = $1) AS exists
`

func (q *Queries) PresentationExistsByID(ctx context.Context, presentationID string) (bool, error) {
	row := q.db.QueryRow(ctx, presentationExistsByID, presentationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePresentation = `-- name: UpdatePresentation :one
UPDATE presentations
SET description = $2
WHERE presentation_id = $1
RETURNING presentation_id, description
`

type UpdatePresentationParams struct {
	PresentationID string      `json:"presentation_id"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) UpdatePresentation(ctx context.Context, arg UpdatePresentationParams) (Presentation, error) {
	row := q.db.QueryRow(ctx, updatePresentation, arg.PresentationID, arg.Description)
	var i Presentation
	err := row.Scan(&i.PresentationID, &i.Description)
	return i, err
}
