// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	ArticleExistsBySku(ctx context.Context, sku string) (bool, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	// Audit logs: who did what, when, how
	// Schema: db/migrations (000003_audit_logs_schema)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateLot(ctx context.Context, arg CreateLotParams) (Lot, error)
	CreatePresentation(ctx context.Context, arg CreatePresentationParams) (Presentation, error)
	CreateSerial(ctx context.Context, arg CreateSerialParams) (Serial, error)
	DeleteArticle(ctx context.Context, id int32) error
	DeleteLocation(ctx context.Context, id int32) error
	DeleteLot(ctx context.Context, id int32) error
	DeletePresentation(ctx context.Context, presentationID string) error
	DeleteSerial(ctx context.Context, id int32) error
	GetArticleByID(ctx context.Context, id int32) (Article, error)
	GetArticleBySku(ctx context.Context, sku string) (Article, error)
	GetLocationByID(ctx context.Context, id int32) (Location, error)
	GetLocationByLocationCode(ctx context.Context, locationCode string) (Location, error)
	GetLotByID(ctx context.Context, id int32) (Lot, error)
	GetPresentationByID(ctx context.Context, presentationID string) (Presentation, error)
	// Serials CRUD for sqlc
	// Schema: db/migrations (serials table)
	GetSerialByID(ctx context.Context, id int32) (Serial, error)
	// Articles CRUD and related queries for sqlc
	// Schema: db/migrations (articles, lots, serials tables)
	ListArticles(ctx context.Context) ([]Article, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// Locations CRUD for sqlc
	// Schema: db/migrations (locations table)
	ListLocations(ctx context.Context) ([]Location, error)
	// Lots CRUD for sqlc
	// Schema: db/migrations (lots table)
	ListLots(ctx context.Context) ([]Lot, error)
	// Lots by SKU (for UpdateArticle warnings)
	ListLotsBySku(ctx context.Context, sku string) ([]Lot, error)
	// Presentations CRUD for sqlc
	// Schema: db/migrations (presentations table)
	ListPresentations(ctx context.Context) ([]Presentation, error)
	// Serials by SKU (for UpdateArticle warnings)
	ListSerialsBySku(ctx context.Context, sku string) ([]Serial, error)
	LocationExistsByLocationCode(ctx context.Context, locationCode string) (bool, error)
	PresentationExistsByID(ctx context.Context, presentationID string) (bool, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateLot(ctx context.Context, arg UpdateLotParams) (Lot, error)
	UpdatePresentation(ctx context.Context, arg UpdatePresentationParams) (Presentation, error)
	UpdateSerial(ctx context.Context, arg UpdateSerialParams) (Serial, error)
}

var _ Querier = (*Queries)(nil)
