// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getRoleByID = `-- name: GetRoleByID :one

SELECT id, name, description, permissions, is_active, created_at, updated_at
FROM roles
WHERE id = $1
LIMIT 1
`

// Roles for RBAC: get by id (role name), get permissions only
// Schema: db/migrations (000004_roles_schema)
func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :one
SELECT permissions
FROM roles
WHERE id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetRolePermissions(ctx context.Context, id string) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getRolePermissions, id)
	var permissions json.RawMessage
	err := row.Scan(&permissions)
	return permissions, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, permissions, is_active, created_at, updated_at
FROM roles
ORDER BY id
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRolePermissions = `-- name: UpdateRolePermissions :one
UPDATE roles
SET permissions = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, description, permissions, is_active, created_at, updated_at
`

type UpdateRolePermissionsParams struct {
	ID          string          `json:"id"`
	Permissions json.RawMessage `json:"permissions"`
}

func (q *Queries) UpdateRolePermissions(ctx context.Context, arg UpdateRolePermissionsParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRolePermissions, arg.ID, arg.Permissions)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
