// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: serials.sql

package sqlc

import (
	"context"
)

const createSerial = `-- name: CreateSerial :one
INSERT INTO serials (serial_number, sku, status)
VALUES ($1, $2, $3)
RETURNING id, serial_number, sku, status, created_at, updated_at
`

type CreateSerialParams struct {
	SerialNumber string `json:"serial_number"`
	Sku          string `json:"sku"`
	Status       string `json:"status"`
}

func (q *Queries) CreateSerial(ctx context.Context, arg CreateSerialParams) (Serial, error) {
	row := q.db.QueryRow(ctx, createSerial, arg.SerialNumber, arg.Sku, arg.Status)
	var i Serial
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.Sku,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSerial = `-- name: DeleteSerial :exec
DELETE FROM serials WHERE id = $1
`

func (q *Queries) DeleteSerial(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSerial, id)
	return err
}

const getSerialByID = `-- name: GetSerialByID :one

SELECT id, serial_number, sku, status, created_at, updated_at
FROM serials
WHERE id = $1
LIMIT 1
`

// Serials CRUD for sqlc
// Schema: db/migrations (serials table)
func (q *Queries) GetSerialByID(ctx context.Context, id int32) (Serial, error) {
	row := q.db.QueryRow(ctx, getSerialByID, id)
	var i Serial
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.Sku,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSerial = `-- name: UpdateSerial :one
UPDATE serials
SET
    serial_number = $2,
    sku = $3,
    status = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, serial_number, sku, status, created_at, updated_at
`

type UpdateSerialParams struct {
	ID           int32  `json:"id"`
	SerialNumber string `json:"serial_number"`
	Sku          string `json:"sku"`
	Status       string `json:"status"`
}

func (q *Queries) UpdateSerial(ctx context.Context, arg UpdateSerialParams) (Serial, error) {
	row := q.db.QueryRow(ctx, updateSerial,
		arg.ID,
		arg.SerialNumber,
		arg.Sku,
		arg.Status,
	)
	var i Serial
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.Sku,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
