// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock_settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStockSettings = `-- name: GetStockSettings :one

SELECT tenant_id, valuation_method, pick_batch_based_on, over_receipt_allowance_pct,
  over_delivery_allowance_pct, over_picking_allowance_pct, auto_reserve_stock,
  allow_partial_reservation, expiry_alert_days, auto_create_material_request,
  partial_delivery_policy, updated_at
FROM stock_settings WHERE tenant_id = $1
`

// StockSettings CRUD for sqlc
// Schema: db/migrations/000018_sprint_s2.up.sql (stock_settings table)
func (q *Queries) GetStockSettings(ctx context.Context, tenantID pgtype.UUID) (StockSetting, error) {
	row := q.db.QueryRow(ctx, getStockSettings, tenantID)
	var i StockSetting
	err := row.Scan(
		&i.TenantID,
		&i.ValuationMethod,
		&i.PickBatchBasedOn,
		&i.OverReceiptAllowancePct,
		&i.OverDeliveryAllowancePct,
		&i.OverPickingAllowancePct,
		&i.AutoReserveStock,
		&i.AllowPartialReservation,
		&i.ExpiryAlertDays,
		&i.AutoCreateMaterialRequest,
		&i.PartialDeliveryPolicy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStockSettings = `-- name: UpsertStockSettings :one
INSERT INTO stock_settings (
  tenant_id, valuation_method, pick_batch_based_on, over_receipt_allowance_pct,
  over_delivery_allowance_pct, over_picking_allowance_pct, auto_reserve_stock,
  allow_partial_reservation, expiry_alert_days, auto_create_material_request,
  partial_delivery_policy
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (tenant_id) DO UPDATE SET
  valuation_method = EXCLUDED.valuation_method,
  pick_batch_based_on = EXCLUDED.pick_batch_based_on,
  over_receipt_allowance_pct = EXCLUDED.over_receipt_allowance_pct,
  over_delivery_allowance_pct = EXCLUDED.over_delivery_allowance_pct,
  over_picking_allowance_pct = EXCLUDED.over_picking_allowance_pct,
  auto_reserve_stock = EXCLUDED.auto_reserve_stock,
  allow_partial_reservation = EXCLUDED.allow_partial_reservation,
  expiry_alert_days = EXCLUDED.expiry_alert_days,
  auto_create_material_request = EXCLUDED.auto_create_material_request,
  partial_delivery_policy = EXCLUDED.partial_delivery_policy,
  updated_at = now()
RETURNING tenant_id, valuation_method, pick_batch_based_on, over_receipt_allowance_pct,
  over_delivery_allowance_pct, over_picking_allowance_pct, auto_reserve_stock,
  allow_partial_reservation, expiry_alert_days, auto_create_material_request,
  partial_delivery_policy, updated_at
`

type UpsertStockSettingsParams struct {
	TenantID                  pgtype.UUID    `json:"tenant_id"`
	ValuationMethod           string         `json:"valuation_method"`
	PickBatchBasedOn          string         `json:"pick_batch_based_on"`
	OverReceiptAllowancePct   pgtype.Numeric `json:"over_receipt_allowance_pct"`
	OverDeliveryAllowancePct  pgtype.Numeric `json:"over_delivery_allowance_pct"`
	OverPickingAllowancePct   pgtype.Numeric `json:"over_picking_allowance_pct"`
	AutoReserveStock          bool           `json:"auto_reserve_stock"`
	AllowPartialReservation   bool           `json:"allow_partial_reservation"`
	ExpiryAlertDays           int32          `json:"expiry_alert_days"`
	AutoCreateMaterialRequest bool           `json:"auto_create_material_request"`
	PartialDeliveryPolicy     string         `json:"partial_delivery_policy"`
}

func (q *Queries) UpsertStockSettings(ctx context.Context, arg UpsertStockSettingsParams) (StockSetting, error) {
	row := q.db.QueryRow(ctx, upsertStockSettings,
		arg.TenantID,
		arg.ValuationMethod,
		arg.PickBatchBasedOn,
		arg.OverReceiptAllowancePct,
		arg.OverDeliveryAllowancePct,
		arg.OverPickingAllowancePct,
		arg.AutoReserveStock,
		arg.AllowPartialReservation,
		arg.ExpiryAlertDays,
		arg.AutoCreateMaterialRequest,
		arg.PartialDeliveryPolicy,
	)
	var i StockSetting
	err := row.Scan(
		&i.TenantID,
		&i.ValuationMethod,
		&i.PickBatchBasedOn,
		&i.OverReceiptAllowancePct,
		&i.OverDeliveryAllowancePct,
		&i.OverPickingAllowancePct,
		&i.AutoReserveStock,
		&i.AllowPartialReservation,
		&i.ExpiryAlertDays,
		&i.AutoCreateMaterialRequest,
		&i.PartialDeliveryPolicy,
		&i.UpdatedAt,
	)
	return i, err
}
