// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock_transfers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockTransfer = `-- name: CreateStockTransfer :one
INSERT INTO stock_transfers (transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
`

type CreateStockTransferParams struct {
	TransferNumber string      `json:"transfer_number"`
	FromLocationID string      `json:"from_location_id"`
	ToLocationID   string      `json:"to_location_id"`
	Status         string      `json:"status"`
	CreatedBy      string      `json:"created_by"`
	AssignedTo     pgtype.Text `json:"assigned_to"`
	Notes          pgtype.Text `json:"notes"`
	DockLocation   pgtype.Text `json:"dock_location"`
}

type CreateStockTransferRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) CreateStockTransfer(ctx context.Context, arg CreateStockTransferParams) (CreateStockTransferRow, error) {
	row := q.db.QueryRow(ctx, createStockTransfer,
		arg.TransferNumber,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.Status,
		arg.CreatedBy,
		arg.AssignedTo,
		arg.Notes,
		arg.DockLocation,
	)
	var i CreateStockTransferRow
	err := row.Scan(
		&i.ID,
		&i.TransferNumber,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Notes,
		&i.DockLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createStockTransferLine = `-- name: CreateStockTransferLine :one
INSERT INTO stock_transfer_lines (stock_transfer_id, sku, quantity, presentation, line_status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, stock_transfer_id, sku, quantity, presentation, line_status, created_at
`

type CreateStockTransferLineParams struct {
	StockTransferID string         `json:"stock_transfer_id"`
	Sku             string         `json:"sku"`
	Quantity        pgtype.Numeric `json:"quantity"`
	Presentation    pgtype.Text    `json:"presentation"`
	LineStatus      string         `json:"line_status"`
}

func (q *Queries) CreateStockTransferLine(ctx context.Context, arg CreateStockTransferLineParams) (StockTransferLine, error) {
	row := q.db.QueryRow(ctx, createStockTransferLine,
		arg.StockTransferID,
		arg.Sku,
		arg.Quantity,
		arg.Presentation,
		arg.LineStatus,
	)
	var i StockTransferLine
	err := row.Scan(
		&i.ID,
		&i.StockTransferID,
		&i.Sku,
		&i.Quantity,
		&i.Presentation,
		&i.LineStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStockTransfer = `-- name: DeleteStockTransfer :exec
DELETE FROM stock_transfers WHERE id = $1
`

func (q *Queries) DeleteStockTransfer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteStockTransfer, id)
	return err
}

const deleteStockTransferLine = `-- name: DeleteStockTransferLine :exec
DELETE FROM stock_transfer_lines WHERE id = $1
`

func (q *Queries) DeleteStockTransferLine(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteStockTransferLine, id)
	return err
}

const deleteStockTransferLinesByTransferID = `-- name: DeleteStockTransferLinesByTransferID :exec
DELETE FROM stock_transfer_lines WHERE stock_transfer_id = $1
`

func (q *Queries) DeleteStockTransferLinesByTransferID(ctx context.Context, stockTransferID string) error {
	_, err := q.db.Exec(ctx, deleteStockTransferLinesByTransferID, stockTransferID)
	return err
}

const getStockTransferByID = `-- name: GetStockTransferByID :one
SELECT id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
FROM stock_transfers
WHERE id = $1
LIMIT 1
`

type GetStockTransferByIDRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) GetStockTransferByID(ctx context.Context, id string) (GetStockTransferByIDRow, error) {
	row := q.db.QueryRow(ctx, getStockTransferByID, id)
	var i GetStockTransferByIDRow
	err := row.Scan(
		&i.ID,
		&i.TransferNumber,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Notes,
		&i.DockLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getStockTransferByTransferNumber = `-- name: GetStockTransferByTransferNumber :one
SELECT id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
FROM stock_transfers
WHERE transfer_number = $1
LIMIT 1
`

type GetStockTransferByTransferNumberRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) GetStockTransferByTransferNumber(ctx context.Context, transferNumber string) (GetStockTransferByTransferNumberRow, error) {
	row := q.db.QueryRow(ctx, getStockTransferByTransferNumber, transferNumber)
	var i GetStockTransferByTransferNumberRow
	err := row.Scan(
		&i.ID,
		&i.TransferNumber,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Notes,
		&i.DockLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getStockTransferLineByID = `-- name: GetStockTransferLineByID :one
SELECT id, stock_transfer_id, sku, quantity, presentation, line_status, created_at
FROM stock_transfer_lines
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStockTransferLineByID(ctx context.Context, id string) (StockTransferLine, error) {
	row := q.db.QueryRow(ctx, getStockTransferLineByID, id)
	var i StockTransferLine
	err := row.Scan(
		&i.ID,
		&i.StockTransferID,
		&i.Sku,
		&i.Quantity,
		&i.Presentation,
		&i.LineStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listStockTransferLinesByTransferID = `-- name: ListStockTransferLinesByTransferID :many
SELECT id, stock_transfer_id, sku, quantity, presentation, line_status, created_at
FROM stock_transfer_lines
WHERE stock_transfer_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListStockTransferLinesByTransferID(ctx context.Context, stockTransferID string) ([]StockTransferLine, error) {
	rows, err := q.db.Query(ctx, listStockTransferLinesByTransferID, stockTransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockTransferLine{}
	for rows.Next() {
		var i StockTransferLine
		if err := rows.Scan(
			&i.ID,
			&i.StockTransferID,
			&i.Sku,
			&i.Quantity,
			&i.Presentation,
			&i.LineStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransfers = `-- name: ListStockTransfers :many

SELECT id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
FROM stock_transfers
ORDER BY created_at DESC
`

type ListStockTransfersRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

// Stock transfers and lines. Schema: db/migrations (stock_transfers, stock_transfer_lines).
func (q *Queries) ListStockTransfers(ctx context.Context) ([]ListStockTransfersRow, error) {
	rows, err := q.db.Query(ctx, listStockTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockTransfersRow{}
	for rows.Next() {
		var i ListStockTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferNumber,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Status,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Notes,
			&i.DockLocation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTransfersByStatus = `-- name: ListStockTransfersByStatus :many
SELECT id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
FROM stock_transfers
WHERE status = $1
ORDER BY created_at DESC
`

type ListStockTransfersByStatusRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) ListStockTransfersByStatus(ctx context.Context, status string) ([]ListStockTransfersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listStockTransfersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockTransfersByStatusRow{}
	for rows.Next() {
		var i ListStockTransfersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferNumber,
			&i.FromLocationID,
			&i.ToLocationID,
			&i.Status,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.Notes,
			&i.DockLocation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockTransfer = `-- name: UpdateStockTransfer :one
UPDATE stock_transfers
SET from_location_id = $2, to_location_id = $3, status = $4, assigned_to = $5, notes = $6, dock_location = $7, updated_at = CURRENT_TIMESTAMP,
    completed_at = CASE WHEN $4 = 'completed' AND status != 'completed' THEN CURRENT_TIMESTAMP ELSE completed_at END
WHERE id = $1
RETURNING id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
`

type UpdateStockTransferParams struct {
	ID             string      `json:"id"`
	FromLocationID string      `json:"from_location_id"`
	ToLocationID   string      `json:"to_location_id"`
	Status         string      `json:"status"`
	AssignedTo     pgtype.Text `json:"assigned_to"`
	Notes          pgtype.Text `json:"notes"`
	DockLocation   pgtype.Text `json:"dock_location"`
}

type UpdateStockTransferRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) UpdateStockTransfer(ctx context.Context, arg UpdateStockTransferParams) (UpdateStockTransferRow, error) {
	row := q.db.QueryRow(ctx, updateStockTransfer,
		arg.ID,
		arg.FromLocationID,
		arg.ToLocationID,
		arg.Status,
		arg.AssignedTo,
		arg.Notes,
		arg.DockLocation,
	)
	var i UpdateStockTransferRow
	err := row.Scan(
		&i.ID,
		&i.TransferNumber,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Notes,
		&i.DockLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateStockTransferLine = `-- name: UpdateStockTransferLine :one
UPDATE stock_transfer_lines
SET quantity = $2, presentation = $3, line_status = $4
WHERE id = $1
RETURNING id, stock_transfer_id, sku, quantity, presentation, line_status, created_at
`

type UpdateStockTransferLineParams struct {
	ID           string         `json:"id"`
	Quantity     pgtype.Numeric `json:"quantity"`
	Presentation pgtype.Text    `json:"presentation"`
	LineStatus   string         `json:"line_status"`
}

func (q *Queries) UpdateStockTransferLine(ctx context.Context, arg UpdateStockTransferLineParams) (StockTransferLine, error) {
	row := q.db.QueryRow(ctx, updateStockTransferLine,
		arg.ID,
		arg.Quantity,
		arg.Presentation,
		arg.LineStatus,
	)
	var i StockTransferLine
	err := row.Scan(
		&i.ID,
		&i.StockTransferID,
		&i.Sku,
		&i.Quantity,
		&i.Presentation,
		&i.LineStatus,
		&i.CreatedAt,
	)
	return i, err
}

const updateStockTransferStatus = `-- name: UpdateStockTransferStatus :one
UPDATE stock_transfers
SET status = $2, updated_at = CURRENT_TIMESTAMP, completed_at = CASE WHEN $2 = 'completed' THEN CURRENT_TIMESTAMP ELSE completed_at END
WHERE id = $1
RETURNING id, transfer_number, from_location_id, to_location_id, status, created_by, assigned_to, notes, dock_location, created_at, updated_at, completed_at
`

type UpdateStockTransferStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

type UpdateStockTransferStatusRow struct {
	ID             string           `json:"id"`
	TransferNumber string           `json:"transfer_number"`
	FromLocationID string           `json:"from_location_id"`
	ToLocationID   string           `json:"to_location_id"`
	Status         string           `json:"status"`
	CreatedBy      string           `json:"created_by"`
	AssignedTo     pgtype.Text      `json:"assigned_to"`
	Notes          pgtype.Text      `json:"notes"`
	DockLocation   pgtype.Text      `json:"dock_location"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CompletedAt    pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) UpdateStockTransferStatus(ctx context.Context, arg UpdateStockTransferStatusParams) (UpdateStockTransferStatusRow, error) {
	row := q.db.QueryRow(ctx, updateStockTransferStatus, arg.ID, arg.Status)
	var i UpdateStockTransferStatusRow
	err := row.Scan(
		&i.ID,
		&i.TransferNumber,
		&i.FromLocationID,
		&i.ToLocationID,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Notes,
		&i.DockLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
