// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_preferences.sql

package sqlc

import (
	"context"
)

const getOrCreateUserPreferences = `-- name: GetOrCreateUserPreferences :one
INSERT INTO user_preferences (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, theme, language, email_notifications, push_notifications,
          marketing_notifications, profile_visibility, data_sharing,
          created_at, updated_by, updated_at
`

func (q *Queries) GetOrCreateUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getOrCreateUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.MarketingNotifications,
		&i.ProfileVisibility,
		&i.DataSharing,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one

SELECT id, user_id, theme, language, email_notifications, push_notifications,
       marketing_notifications, profile_visibility, data_sharing,
       created_at, updated_by, updated_at
FROM user_preferences
WHERE user_id = $1
`

// User preferences: get, update, get-or-create (from backend_template)
func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.MarketingNotifications,
		&i.ProfileVisibility,
		&i.DataSharing,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences SET
  theme = $2,
  language = $3,
  email_notifications = $4,
  push_notifications = $5,
  marketing_notifications = $6,
  profile_visibility = $7,
  data_sharing = $8
WHERE user_id = $1
RETURNING id, user_id, theme, language, email_notifications, push_notifications,
          marketing_notifications, profile_visibility, data_sharing,
          created_at, updated_by, updated_at
`

type UpdateUserPreferencesParams struct {
	UserID                 string `json:"user_id"`
	Theme                  string `json:"theme"`
	Language               string `json:"language"`
	EmailNotifications     bool   `json:"email_notifications"`
	PushNotifications      bool   `json:"push_notifications"`
	MarketingNotifications bool   `json:"marketing_notifications"`
	ProfileVisibility      string `json:"profile_visibility"`
	DataSharing            bool   `json:"data_sharing"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.EmailNotifications,
		arg.PushNotifications,
		arg.MarketingNotifications,
		arg.ProfileVisibility,
		arg.DataSharing,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.MarketingNotifications,
		&i.ProfileVisibility,
		&i.DataSharing,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
